// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_SplashScreen
void ui_SplashScreen_screen_init(void);
void ui_event_SplashScreen(lv_event_t * e);
lv_obj_t * ui_SplashScreen;
lv_obj_t * ui_SplashScreenLogo;


// SCREEN: ui_StatsScreen
void ui_StatsScreen_screen_init(void);
void ui_event_StatsScreen(lv_event_t * e);
lv_obj_t * ui_StatsScreen;
lv_obj_t * ui_DutyCycle;
lv_obj_t * ui_Utilizaiton;
lv_obj_t * ui_LeftSensor;
lv_obj_t * ui_RightSensor;
lv_obj_t * ui_StatsContent;
lv_obj_t * ui_StatsHeader;
lv_obj_t * ui_MessageText;
lv_obj_t * ui_StatsBody;
lv_obj_t * ui_PrimaryStat;
lv_obj_t * ui_PrimaryStatUnit;
lv_obj_t * ui_SecondaryStats;
lv_obj_t * ui_ConnectionState;
lv_obj_t * ui_DistanceStats;
lv_obj_t * ui_TempStats;
lv_obj_t * ui_StatsFooter;
void ui_event_BatteryDisplay(lv_event_t * e);
lv_obj_t * ui_BatteryDisplay;


// SCREEN: ui_SettingsScreen
void ui_SettingsScreen_screen_init(void);
lv_obj_t * ui_SettingsScreen;
lv_obj_t * ui_Content;
lv_obj_t * ui_SettingsBody;
void ui_event_SettingsBackButton(lv_event_t * e);
lv_obj_t * ui_SettingsBackButton;
lv_obj_t * ui_SettingsBackButtonLabel;
lv_obj_t * ui_SettingsCategoryLabel;
void ui_event_SettingsBrightnessButton(lv_event_t * e);
lv_obj_t * ui_SettingsBrightnessButton;
lv_obj_t * ui_SettingsBrightnessButtonLabel;
void ui_event_SettingsPowerButton(lv_event_t * e);
lv_obj_t * ui_SettingsPowerButton;
lv_obj_t * ui_SettingsPowerButtonLabel;
void ui_event_SettingsCalibrateButton(lv_event_t * e);
lv_obj_t * ui_SettingsCalibrateButton;
lv_obj_t * ui_SettingsCalibrateButtonLabel;
lv_obj_t * ui_ActionsCategoryLabel;
void ui_event_SettingsPairButton(lv_event_t * e);
lv_obj_t * ui_SettingsPairButton;
lv_obj_t * ui_SettingsPairButtonLabel;
void ui_event_SettingsShutdownButton(lv_event_t * e);
lv_obj_t * ui_SettingsShutdownButton;
lv_obj_t * ui_SettingsShutdownButtonLabel;


// SCREEN: ui_BrightnessScreen
void ui_BrightnessScreen_screen_init(void);
lv_obj_t * ui_BrightnessScreen;
lv_obj_t * ui_BrightnessContent;
lv_obj_t * ui_BrightnessHeader;
lv_obj_t * ui_BrightnessBody;
lv_obj_t * ui_BrightnessSlider;
lv_obj_t * ui_BrightnessLabel;
lv_obj_t * ui_BrightnessFooter;
void ui_event_BrightnessMainActionButton(lv_event_t * e);
lv_obj_t * ui_BrightnessMainActionButton;
lv_obj_t * ui_BrightnessMainActionButtonLabel;


// SCREEN: ui_PairingScreen
void ui_PairingScreen_screen_init(void);
void ui_event_PairingScreen(lv_event_t * e);
lv_obj_t * ui_PairingScreen;
lv_obj_t * ui_PairingContent;
lv_obj_t * ui_PairingHeader;
lv_obj_t * ui_PairingBody;
lv_obj_t * ui_PairingCode;
lv_obj_t * ui_PairingCodeLabel;
lv_obj_t * ui_PairingFooter;
void ui_event_PairingMainActionButton(lv_event_t * e);
lv_obj_t * ui_PairingMainActionButton;
lv_obj_t * ui_PairingMainActionButtonLabel;


// SCREEN: ui_PowerScreen
void ui_PowerScreen_screen_init(void);
void ui_event_PowerScreen(lv_event_t * e);
lv_obj_t * ui_PowerScreen;
lv_obj_t * ui_PowerContent;
lv_obj_t * ui_PowerHeader;
lv_obj_t * ui_PowerBody;
lv_obj_t * ui_AutoOffTime;
lv_obj_t * ui_PowerLabel;
lv_obj_t * ui_PowerFooter;
void ui_event_PowerMainActionButton(lv_event_t * e);
lv_obj_t * ui_PowerMainActionButton;
lv_obj_t * ui_PowerMainActionButtonLabel;


// SCREEN: ui_CalibrationScreen
void ui_CalibrationScreen_screen_init(void);
lv_obj_t * ui_CalibrationScreen;
lv_obj_t * ui_CalibrationContent;
lv_obj_t * ui_CalibrationHeader;
lv_obj_t * ui_CalibrationBody;
lv_obj_t * ui_PowerLabel1;
lv_obj_t * ui_CalibrationOption;
lv_obj_t * ui_CalibrationFooter;
void ui_event_CalibrationMainActionButton(lv_event_t * e);
lv_obj_t * ui_CalibrationMainActionButton;
lv_obj_t * ui_CalibrationMainActionButtonLabel;
lv_obj_t * ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=1
    #error "LV_COLOR_16_SWAP should be 1 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_SplashScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        _ui_screen_change(&ui_StatsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1000, &ui_StatsScreen_screen_init);
    }
}
void ui_event_StatsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_OVER_BOTTOM, 200, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_BatteryDisplay(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_LONG_PRESSED) {
        toggleFooterDisplayMode(e);
    }
}
void ui_event_SettingsBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StatsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_StatsScreen_screen_init);
    }
}
void ui_event_SettingsBrightnessButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_BrightnessScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_BrightnessScreen_screen_init);
    }
}
void ui_event_SettingsPowerButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PowerScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_PowerScreen_screen_init);
    }
}
void ui_event_SettingsCalibrateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibrationScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_CalibrationScreen_screen_init);
    }
}
void ui_event_SettingsPairButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PairingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_PairingScreen_screen_init);
    }
}
void ui_event_SettingsShutdownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        enter_deep_sleep(e);
    }
}
void ui_event_BrightnessMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_PairingScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        StartPairing(e);
    }
}
void ui_event_PairingMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_PowerScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_SCREEN_LOADED) {
        StartPairing(e);
    }
}
void ui_event_PowerMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}
void ui_event_CalibrationMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);
    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               true, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_SplashScreen_screen_init();
    ui_StatsScreen_screen_init();
    ui_SettingsScreen_screen_init();
    ui_BrightnessScreen_screen_init();
    ui_PairingScreen_screen_init();
    ui_PowerScreen_screen_init();
    ui_CalibrationScreen_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_SplashScreen);
}
