// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

void ui_BrightnessScreen_screen_init(void)
{
    ui_BrightnessScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_BrightnessScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessContent = lv_obj_create(ui_BrightnessScreen);
    lv_obj_remove_style_all(ui_BrightnessContent);
    lv_obj_set_width(ui_BrightnessContent, lv_pct(100));
    lv_obj_set_height(ui_BrightnessContent, lv_pct(100));
    lv_obj_set_align(ui_BrightnessContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrightnessContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessHeader = lv_obj_create(ui_BrightnessContent);
    lv_obj_remove_style_all(ui_BrightnessHeader);
    lv_obj_set_width(ui_BrightnessHeader, 100);
    lv_obj_set_height(ui_BrightnessHeader, lv_pct(25));
    lv_obj_set_align(ui_BrightnessHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessBody = lv_obj_create(ui_BrightnessContent);
    lv_obj_remove_style_all(ui_BrightnessBody);
    lv_obj_set_width(ui_BrightnessBody, lv_pct(65));
    lv_obj_set_height(ui_BrightnessBody, lv_pct(50));
    lv_obj_set_align(ui_BrightnessBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrightnessBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessBody, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_BrightnessBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessBody, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessBody, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_BrightnessBody);
    lv_slider_set_value(ui_BrightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_height(ui_BrightnessSlider, 10);
    lv_obj_set_width(ui_BrightnessSlider, lv_pct(100));
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);


    ui_BrightnessLabel = lv_label_create(ui_BrightnessBody);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLabel, 19);
    lv_obj_set_y(ui_BrightnessLabel, 38);
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessLabel, "Screen brightness");

    ui_BrightnessFooter = lv_obj_create(ui_BrightnessContent);
    lv_obj_remove_style_all(ui_BrightnessFooter);
    lv_obj_set_width(ui_BrightnessFooter, lv_pct(65));
    lv_obj_set_height(ui_BrightnessFooter, lv_pct(25));
    lv_obj_set_align(ui_BrightnessFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_BrightnessFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_BrightnessFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_BrightnessFooter, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessFooter, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessFooter, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessMainActionButton = lv_btn_create(ui_BrightnessFooter);
    lv_obj_set_width(ui_BrightnessMainActionButton, 80);
    lv_obj_set_height(ui_BrightnessMainActionButton, 42);
    lv_obj_set_align(ui_BrightnessMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_BrightnessMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_BrightnessMainActionButtonLabel = lv_label_create(ui_BrightnessMainActionButton);
    lv_obj_set_width(ui_BrightnessMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessMainActionButtonLabel, "Save");

    lv_obj_add_event_cb(ui_BrightnessMainActionButton, ui_event_BrightnessMainActionButton, LV_EVENT_ALL, NULL);

}
