// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: PubRemote

#include "ui.h"

void ui_CalibrationScreen_screen_init(void)
{
    ui_CalibrationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenContent = lv_obj_create(ui_CalibrationScreen);
    lv_obj_remove_style_all(ui_CalibrationScreenContent);
    lv_obj_set_width(ui_CalibrationScreenContent, lv_pct(100));
    lv_obj_set_height(ui_CalibrationScreenContent, lv_pct(100));
    lv_obj_set_align(ui_CalibrationScreenContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenHeader = lv_obj_create(ui_CalibrationScreenContent);
    lv_obj_remove_style_all(ui_CalibrationScreenHeader);
    lv_obj_set_width(ui_CalibrationScreenHeader, 100);
    lv_obj_set_height(ui_CalibrationScreenHeader, 50);
    lv_obj_set_align(ui_CalibrationScreenHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenBody = lv_obj_create(ui_CalibrationScreenContent);
    lv_obj_remove_style_all(ui_CalibrationScreenBody);
    lv_obj_set_width(ui_CalibrationScreenBody, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_CalibrationScreenBody, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_CalibrationScreenBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenFooter = lv_obj_create(ui_CalibrationScreenContent);
    lv_obj_remove_style_all(ui_CalibrationScreenFooter);
    lv_obj_set_width(ui_CalibrationScreenFooter, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_CalibrationScreenFooter, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_CalibrationScreenFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenFooter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenFooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CalibrationScreenFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_CalibrationScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrationScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrationScreenFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrationScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationScreenMainActionButton = lv_btn_create(ui_CalibrationScreenFooter);
    lv_obj_set_width(ui_CalibrationScreenMainActionButton, 100);
    lv_obj_set_height(ui_CalibrationScreenMainActionButton, 37);
    lv_obj_set_x(ui_CalibrationScreenMainActionButton, lv_pct(-27));
    lv_obj_set_y(ui_CalibrationScreenMainActionButton, lv_pct(-514));
    lv_obj_set_align(ui_CalibrationScreenMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationScreenMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationScreenMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenMainActionButtonLabel = lv_label_create(ui_CalibrationScreenMainActionButton);
    lv_obj_set_width(ui_CalibrationScreenMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationScreenMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_CalibrationScreenMainActionButtonLabel, 0);
    lv_obj_set_y(ui_CalibrationScreenMainActionButtonLabel, -1);
    lv_obj_set_align(ui_CalibrationScreenMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationScreenMainActionButtonLabel, "Calibrate");

    lv_obj_add_event_cb(ui_CalibrationScreenMainActionButton, ui_event_CalibrationScreenMainActionButton, LV_EVENT_ALL,
                        NULL);
    lv_obj_add_event_cb(ui_CalibrationScreen, ui_event_CalibrationScreen, LV_EVENT_ALL, NULL);

}
