// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

void ui_CalibrationScreen_screen_init(void)
{
    ui_CalibrationScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationContent = lv_obj_create(ui_CalibrationScreen);
    lv_obj_remove_style_all(ui_CalibrationContent);
    lv_obj_set_width(ui_CalibrationContent, lv_pct(100));
    lv_obj_set_height(ui_CalibrationContent, lv_pct(100));
    lv_obj_set_align(ui_CalibrationContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_CalibrationContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationHeader = lv_obj_create(ui_CalibrationContent);
    lv_obj_remove_style_all(ui_CalibrationHeader);
    lv_obj_set_width(ui_CalibrationHeader, 100);
    lv_obj_set_height(ui_CalibrationHeader, lv_pct(25));
    lv_obj_set_align(ui_CalibrationHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationBody = lv_obj_create(ui_CalibrationContent);
    lv_obj_remove_style_all(ui_CalibrationBody);
    lv_obj_set_width(ui_CalibrationBody, lv_pct(65));
    lv_obj_set_height(ui_CalibrationBody, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_CalibrationBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_CalibrationBody, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalibrationBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PowerLabel1 = lv_label_create(ui_CalibrationBody);
    lv_obj_set_width(ui_PowerLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerLabel1, 19);
    lv_obj_set_y(ui_PowerLabel1, 38);
    lv_obj_set_align(ui_PowerLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerLabel1, "X: 0 | Y: 0");
    lv_obj_set_style_text_font(ui_PowerLabel1, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationOption = lv_dropdown_create(ui_CalibrationBody);
    lv_dropdown_set_options(ui_CalibrationOption, "Centering\nY deadzone\nX deadzone\n");
    lv_obj_set_width(ui_CalibrationOption, 150);
    lv_obj_set_height(ui_CalibrationOption, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationOption, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationOption, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_CalibrationOption, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_CalibrationOption, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_CalibrationOption), &ui_font_Inter_14,
                               LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationFooter = lv_obj_create(ui_CalibrationContent);
    lv_obj_remove_style_all(ui_CalibrationFooter);
    lv_obj_set_width(ui_CalibrationFooter, lv_pct(65));
    lv_obj_set_height(ui_CalibrationFooter, lv_pct(25));
    lv_obj_set_align(ui_CalibrationFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_CalibrationFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CalibrationFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_CalibrationFooter, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrationFooter, 48, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrationFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrationFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_CalibrationFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_CalibrationFooter, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationMainActionButton = lv_btn_create(ui_CalibrationFooter);
    lv_obj_set_width(ui_CalibrationMainActionButton, 80);
    lv_obj_set_height(ui_CalibrationMainActionButton, 42);
    lv_obj_set_align(ui_CalibrationMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_CalibrationMainActionButton, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationMainActionButtonLabel = lv_label_create(ui_CalibrationMainActionButton);
    lv_obj_set_width(ui_CalibrationMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationMainActionButtonLabel, "Save");

    lv_obj_add_event_cb(ui_CalibrationMainActionButton, ui_event_CalibrationMainActionButton, LV_EVENT_ALL, NULL);

}
