// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: PubRemote

#include "ui.h"

void ui_CalibrationScreen1_screen_init(void)
{
    ui_CalibrationScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_CalibrationScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenContent1 = lv_obj_create(ui_CalibrationScreen1);
    lv_obj_remove_style_all(ui_CalibrationScreenContent1);
    lv_obj_set_width(ui_CalibrationScreenContent1, lv_pct(100));
    lv_obj_set_height(ui_CalibrationScreenContent1, lv_pct(100));
    lv_obj_set_align(ui_CalibrationScreenContent1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenContent1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenContent1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenContent1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenheader1 = lv_obj_create(ui_CalibrationScreenContent1);
    lv_obj_remove_style_all(ui_CalibrationScreenheader1);
    lv_obj_set_width(ui_CalibrationScreenheader1, 100);
    lv_obj_set_height(ui_CalibrationScreenheader1, 50);
    lv_obj_set_align(ui_CalibrationScreenheader1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenheader1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenBody1 = lv_obj_create(ui_CalibrationScreenContent1);
    lv_obj_remove_style_all(ui_CalibrationScreenBody1);
    lv_obj_set_width(ui_CalibrationScreenBody1, lv_pct(100));
    lv_obj_set_height(ui_CalibrationScreenBody1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_CalibrationScreenBody1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenBody1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenBody1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_CalibrationScreenBody1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label1 = lv_label_create(ui_CalibrationScreenBody1);
    lv_obj_set_width(ui_Label1, lv_pct(80));
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 19);
    lv_obj_set_y(ui_Label1, 38);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Move joystick/throttle to min and max values\n\nPress done when complete");
    lv_obj_set_style_text_align(ui_Label1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationScreenFooter1 = lv_obj_create(ui_CalibrationScreenContent1);
    lv_obj_remove_style_all(ui_CalibrationScreenFooter1);
    lv_obj_set_width(ui_CalibrationScreenFooter1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_CalibrationScreenFooter1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_CalibrationScreenFooter1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_CalibrationScreenFooter1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_CalibrationScreenFooter1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_CalibrationScreenFooter1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_CalibrationScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_CalibrationScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_CalibrationScreenFooter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_CalibrationScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_CalibrationScreenMainActionButton1 = lv_btn_create(ui_CalibrationScreenFooter1);
    lv_obj_set_width(ui_CalibrationScreenMainActionButton1, 100);
    lv_obj_set_height(ui_CalibrationScreenMainActionButton1, 37);
    lv_obj_set_align(ui_CalibrationScreenMainActionButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CalibrationScreenMainActionButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_CalibrationScreenMainActionButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CalibrationScreenMainActionButtonLabel1 = lv_label_create(ui_CalibrationScreenMainActionButton1);
    lv_obj_set_width(ui_CalibrationScreenMainActionButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_CalibrationScreenMainActionButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_CalibrationScreenMainActionButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_CalibrationScreenMainActionButtonLabel1, "Done");

    lv_obj_add_event_cb(ui_CalibrationScreenMainActionButton1, ui_event_CalibrationScreenMainActionButton1, LV_EVENT_ALL,
                        NULL);

}
