// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: PubRemote
#include "../src/remote/receiver.h"
#include "ui.h"
static const char *TAG = "UI-EVENTS";
void toggleFooterDisplayMode(lv_event_t *e) {
  // Your code here
}

void StartPairing(lv_event_t *e) {
  pairing_state = 1;
}

void CompleteCalibration(lv_event_t *e) {
  // Your code here
}
