// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"
#include <remote/display.h>
#include <remote/powermanagement.h>
#include <remote/settings.h>

void stats_footer_long_press(lv_event_t *e) {
  // Your code here
}

void enter_deep_sleep(lv_event_t *e) {
  enter_sleep();
}

void brightness_screen_loaded(lv_event_t *e) {
  lv_slider_set_value(ui_BrightnessSlider, settings.bl_level, LV_ANIM_OFF);
}

void brightness_slider_change(lv_event_t *e) {
  int val = lv_slider_get_value(ui_BrightnessSlider);
  settings.bl_level = (uint8_t)val;
  set_bl_level(settings.bl_level);
}

void brightness_save(lv_event_t *e) {
  save_bl_level();
}

void pairing_screen_loaded(lv_event_t *e) {
  // Your code here
}

void power_screen_loaded(lv_event_t *e) {
  lv_dropdown_set_selected(ui_AutoOffTime, settings.auto_off_time);
}

void auto_off_select_change(lv_event_t *e) {
  int val = lv_dropdown_get_selected(ui_AutoOffTime);
  // TODO - don't just use index value
  settings.auto_off_time = (uint8_t)(val & 0xFF);
}

void power_settings_save(lv_event_t *e) {
  save_auto_off_time();
}

void calibration_settings_save(lv_event_t *e) {
  // Your code here
}
