// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 8.3.6
// Project name: PubRemote

#include "ui.h"

void ui_PairingScreen_screen_init(void)
{
    ui_PairingScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PairingScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenContent = lv_obj_create(ui_PairingScreen);
    lv_obj_remove_style_all(ui_PairingScreenContent);
    lv_obj_set_width(ui_PairingScreenContent, lv_pct(100));
    lv_obj_set_height(ui_PairingScreenContent, lv_pct(100));
    lv_obj_set_align(ui_PairingScreenContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenHeader = lv_obj_create(ui_PairingScreenContent);
    lv_obj_remove_style_all(ui_PairingScreenHeader);
    lv_obj_set_width(ui_PairingScreenHeader, 100);
    lv_obj_set_height(ui_PairingScreenHeader, 50);
    lv_obj_set_align(ui_PairingScreenHeader, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenBody = lv_obj_create(ui_PairingScreenContent);
    lv_obj_remove_style_all(ui_PairingScreenBody);
    lv_obj_set_width(ui_PairingScreenBody, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PairingScreenBody, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PairingScreenBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label2 = lv_label_create(ui_PairingScreenBody);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "1337");
    lv_obj_set_style_text_font(ui_Label2, &ui_font_Open_Sans_Bold_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label1 = lv_label_create(ui_PairingScreenBody);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, 19);
    lv_obj_set_y(ui_Label1, 38);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Your pairing code");

    ui_PairingScreenFooter = lv_obj_create(ui_PairingScreenContent);
    lv_obj_remove_style_all(ui_PairingScreenFooter);
    lv_obj_set_width(ui_PairingScreenFooter, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PairingScreenFooter, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PairingScreenFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenFooter, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenFooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PairingScreenFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PairingScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PairingScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PairingScreenFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PairingScreenFooter, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PairingScreenMainActionButton = lv_btn_create(ui_PairingScreenFooter);
    lv_obj_set_width(ui_PairingScreenMainActionButton, 100);
    lv_obj_set_height(ui_PairingScreenMainActionButton, 37);
    lv_obj_set_align(ui_PairingScreenMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PairingScreenMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PairingScreenMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenMainActionButtonLabel = lv_label_create(ui_PairingScreenMainActionButton);
    lv_obj_set_width(ui_PairingScreenMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PairingScreenMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PairingScreenMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PairingScreenMainActionButtonLabel, "Cancel");

    lv_obj_add_event_cb(ui_PairingScreenMainActionButton, ui_event_PairingScreenMainActionButton, LV_EVENT_ALL, NULL);

}
