// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.1
// LVGL version: 8.3.6
// Project name: PubRemote

#include "ui.h"

void ui_PairingScreen1_screen_init(void)
{
    ui_PairingScreen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_PairingScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenContent1 = lv_obj_create(ui_PairingScreen1);
    lv_obj_remove_style_all(ui_PairingScreenContent1);
    lv_obj_set_width(ui_PairingScreenContent1, lv_pct(100));
    lv_obj_set_height(ui_PairingScreenContent1, lv_pct(100));
    lv_obj_set_align(ui_PairingScreenContent1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenContent1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenContent1, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenContent1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenHeader1 = lv_obj_create(ui_PairingScreenContent1);
    lv_obj_remove_style_all(ui_PairingScreenHeader1);
    lv_obj_set_width(ui_PairingScreenHeader1, 100);
    lv_obj_set_height(ui_PairingScreenHeader1, 50);
    lv_obj_set_align(ui_PairingScreenHeader1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenHeader1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenBody1 = lv_obj_create(ui_PairingScreenContent1);
    lv_obj_remove_style_all(ui_PairingScreenBody1);
    lv_obj_set_width(ui_PairingScreenBody1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PairingScreenBody1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PairingScreenBody1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenBody1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenBody1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PairingScreenBody1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label3 = lv_label_create(ui_PairingScreenBody1);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "1337");
    lv_obj_set_style_text_font(ui_Label3, &ui_font_Open_Sans_Bold_48, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label5 = lv_label_create(ui_PairingScreenBody1);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, 19);
    lv_obj_set_y(ui_Label5, 38);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Your pairing code");

    ui_PairingScreenFooter1 = lv_obj_create(ui_PairingScreenContent1);
    lv_obj_remove_style_all(ui_PairingScreenFooter1);
    lv_obj_set_width(ui_PairingScreenFooter1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_PairingScreenFooter1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_align(ui_PairingScreenFooter1, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PairingScreenFooter1, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PairingScreenFooter1, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PairingScreenFooter1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_PairingScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PairingScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PairingScreenFooter1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PairingScreenFooter1, 24, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PairingScreenMainActionButton1 = lv_btn_create(ui_PairingScreenFooter1);
    lv_obj_set_width(ui_PairingScreenMainActionButton1, 100);
    lv_obj_set_height(ui_PairingScreenMainActionButton1, 37);
    lv_obj_set_align(ui_PairingScreenMainActionButton1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_PairingScreenMainActionButton1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_PairingScreenMainActionButton1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PairingScreenMainActionButtonLabel1 = lv_label_create(ui_PairingScreenMainActionButton1);
    lv_obj_set_width(ui_PairingScreenMainActionButtonLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PairingScreenMainActionButtonLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PairingScreenMainActionButtonLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PairingScreenMainActionButtonLabel1, "Cancel");

    lv_obj_add_event_cb(ui_PairingScreenMainActionButton1, ui_event_PairingScreenMainActionButton1, LV_EVENT_ALL, NULL);

}
