// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: PubRemote

#include "ui.h"

void ui_SettingsScreen_screen_init(void)
{
ui_SettingsScreen = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsScreenContent = lv_obj_create(ui_SettingsScreen);
lv_obj_remove_style_all(ui_SettingsScreenContent);
lv_obj_set_width( ui_SettingsScreenContent, lv_pct(100));
lv_obj_set_height( ui_SettingsScreenContent, lv_pct(100));
lv_obj_set_align( ui_SettingsScreenContent, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreenContent,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsScreenContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SettingsScreenContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsScreenHeader = lv_obj_create(ui_SettingsScreenContent);
lv_obj_remove_style_all(ui_SettingsScreenHeader);
lv_obj_set_width( ui_SettingsScreenHeader, 100);
lv_obj_set_height( ui_SettingsScreenHeader, 50);
lv_obj_set_align( ui_SettingsScreenHeader, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_SettingsScreenHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsScreenBody = lv_obj_create(ui_SettingsScreenContent);
lv_obj_remove_style_all(ui_SettingsScreenBody);
lv_obj_set_height( ui_SettingsScreenBody, lv_pct(50));
lv_obj_set_width( ui_SettingsScreenBody, LV_SIZE_CONTENT);  /// 100
lv_obj_set_align( ui_SettingsScreenBody, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreenBody,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsScreenBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_add_flag( ui_SettingsScreenBody, LV_OBJ_FLAG_OVERFLOW_VISIBLE );   /// Flags
lv_obj_clear_flag( ui_SettingsScreenBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SettingsScreenBody, 12, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SettingsScreenBody, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BrightnessSlider = lv_slider_create(ui_SettingsScreenBody);
lv_slider_set_value( ui_BrightnessSlider, 0, LV_ANIM_OFF);
if (lv_slider_get_mode(ui_BrightnessSlider)==LV_SLIDER_MODE_RANGE ) lv_slider_set_left_value( ui_BrightnessSlider, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BrightnessSlider, 150);
lv_obj_set_height( ui_BrightnessSlider, 10);
lv_obj_set_align( ui_BrightnessSlider, LV_ALIGN_CENTER );


ui_BrightnessLabel = lv_label_create(ui_SettingsScreenBody);
lv_obj_set_width( ui_BrightnessLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BrightnessLabel, 19 );
lv_obj_set_y( ui_BrightnessLabel, 48 );
lv_obj_set_align( ui_BrightnessLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_BrightnessLabel,"Brightness");

ui_SettingsScreenFooter = lv_obj_create(ui_SettingsScreenContent);
lv_obj_remove_style_all(ui_SettingsScreenFooter);
lv_obj_set_width( ui_SettingsScreenFooter, LV_SIZE_CONTENT);  /// 100
lv_obj_set_height( ui_SettingsScreenFooter, LV_SIZE_CONTENT);   /// 50
lv_obj_set_align( ui_SettingsScreenFooter, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SettingsScreenFooter,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SettingsScreenFooter, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SettingsScreenFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_left(ui_SettingsScreenFooter, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_right(ui_SettingsScreenFooter, 24, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_top(ui_SettingsScreenFooter, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_bottom(ui_SettingsScreenFooter, 24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsScreenMainActionButton = lv_btn_create(ui_SettingsScreenFooter);
lv_obj_set_width( ui_SettingsScreenMainActionButton, 100);
lv_obj_set_height( ui_SettingsScreenMainActionButton, 37);
lv_obj_set_align( ui_SettingsScreenMainActionButton, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_SettingsScreenMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_SettingsScreenMainActionButton, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SettingsScreenMainActionButtonLabel = lv_label_create(ui_SettingsScreenMainActionButton);
lv_obj_set_width( ui_SettingsScreenMainActionButtonLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsScreenMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SettingsScreenMainActionButtonLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsScreenMainActionButtonLabel,"Save");

lv_obj_add_event_cb(ui_SettingsScreenMainActionButton, ui_event_SettingsScreenMainActionButton, LV_EVENT_ALL, NULL);

}
