// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.6
// Project name: PubRemote

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_PRIMARY 0
#define UI_THEME_COLOR_ACCENT 1
#define UI_THEME_COLOR_SUCCESS 2
#define UI_THEME_COLOR_ERROR 3
#define UI_THEME_COLOR_WARN 4

#define UI_THEME_DEFAULT 0

extern const ui_theme_variable_t _ui_theme_color_Primary[1];
extern const ui_theme_variable_t _ui_theme_alpha_Primary[1];

extern const ui_theme_variable_t _ui_theme_color_Accent[1];
extern const ui_theme_variable_t _ui_theme_alpha_Accent[1];

extern const ui_theme_variable_t _ui_theme_color_Success[1];
extern const ui_theme_variable_t _ui_theme_alpha_Success[1];

extern const ui_theme_variable_t _ui_theme_color_Error[1];
extern const ui_theme_variable_t _ui_theme_alpha_Error[1];

extern const ui_theme_variable_t _ui_theme_color_Warn[1];
extern const ui_theme_variable_t _ui_theme_alpha_Warn[1];

extern const uint32_t* ui_theme_colors[1];
extern const uint8_t* ui_theme_alphas[1];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
