// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Primary[1] = {0x5465FF};
const ui_theme_variable_t _ui_theme_alpha_Primary[1] = {255};

const ui_theme_variable_t _ui_theme_color_Accent[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Accent[1] = {255};

const ui_theme_variable_t _ui_theme_color_Success[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Success[1] = {255};

const ui_theme_variable_t _ui_theme_color_Error[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Error[1] = {255};

const ui_theme_variable_t _ui_theme_color_Warn[1] = {0x000000};
const ui_theme_variable_t _ui_theme_alpha_Warn[1] = {255};
uint8_t ui_theme_idx = UI_THEME_DEFAULT;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

