// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_ABOUTSCREEN_H
#define UI_ABOUTSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AboutScreen
extern void ui_AboutScreen_screen_init(void);
extern void ui_AboutScreen_screen_destroy(void);
extern void ui_event_AboutScreen(lv_event_t * e);
extern lv_obj_t * ui_AboutScreen;
extern lv_obj_t * ui_AboutContent;
extern lv_obj_t * ui_AboutHeader;
extern lv_obj_t * ui_AboutBody;
extern lv_obj_t * ui_VersionInfoContainer;
extern lv_obj_t * ui_VersionInfoLabel;
extern void ui_event_UpdateButton(lv_event_t * e);
extern lv_obj_t * ui_UpdateButton;
extern lv_obj_t * ui_UpdateButtonLabel;
extern lv_obj_t * ui_DebugInfoContainer;
extern lv_obj_t * ui_DebugInfoLabel;
extern lv_obj_t * ui_AboutFooter;
extern void ui_event_AboutMainActionButton(lv_event_t * e);
extern lv_obj_t * ui_AboutMainActionButton;
extern lv_obj_t * ui_AboutMainActionButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

