// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

lv_obj_t * ui_AboutScreen = NULL;
lv_obj_t * ui_AboutContent = NULL;
lv_obj_t * ui_AboutHeader = NULL;
lv_obj_t * ui_AboutBody = NULL;
lv_obj_t * ui_VersionInfoContainer = NULL;
lv_obj_t * ui_VersionInfoLabel = NULL;
lv_obj_t * ui_DebugInfoContainer = NULL;
lv_obj_t * ui_DebugInfoLabel = NULL;
lv_obj_t * ui_AboutFooter = NULL;
lv_obj_t * ui_AboutMainActionButton = NULL;
lv_obj_t * ui_AboutMainActionButtonLabel = NULL;
lv_obj_t * ui_UpdateButton = NULL;
lv_obj_t * ui_UpdateButtonLabel = NULL;
// event funtions
void ui_event_AboutScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        about_screen_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        about_screen_unload_start(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        about_screen_load_start(e);
    }
}

void ui_event_AboutMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MenuScreen_screen_init);
    }
}

void ui_event_UpdateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_UpdateScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_UpdateScreen_screen_init);
    }
}

// build funtions

void ui_AboutScreen_screen_init(void)
{
    ui_AboutScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_AboutScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_AboutScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_AboutScreen);
    lv_obj_set_style_bg_color(ui_AboutScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_AboutScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutContent = lv_obj_create(ui_AboutScreen);
    lv_obj_remove_style_all(ui_AboutContent);
    lv_obj_set_width(ui_AboutContent, lv_pct(100));
    lv_obj_set_height(ui_AboutContent, lv_pct(100));
    lv_obj_set_align(ui_AboutContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_AboutContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AboutContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_AboutContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutHeader = lv_obj_create(ui_AboutContent);
    lv_obj_remove_style_all(ui_AboutHeader);
    lv_obj_set_width(ui_AboutHeader, lv_pct(100));
    lv_obj_set_height(ui_AboutHeader, lv_pct(20));
    lv_obj_set_align(ui_AboutHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AboutHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AboutHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AboutHeader, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_AboutHeader, LV_DIR_VER);
    lv_obj_set_style_pad_left(ui_AboutHeader, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_AboutHeader, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_AboutHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_AboutHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_AboutHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AboutHeader, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutBody = lv_obj_create(ui_AboutContent);
    lv_obj_remove_style_all(ui_AboutBody);
    lv_obj_set_width(ui_AboutBody, lv_pct(100));
    lv_obj_set_height(ui_AboutBody, lv_pct(55));
    lv_obj_set_align(ui_AboutBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutBody, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AboutBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AboutBody, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_AboutBody, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_AboutBody, LV_DIR_HOR);
    lv_obj_set_scroll_snap_x(ui_AboutBody, LV_SCROLL_SNAP_START);

    ui_VersionInfoContainer = lv_obj_create(ui_AboutBody);
    lv_obj_remove_style_all(ui_VersionInfoContainer);
    lv_obj_set_width(ui_VersionInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_VersionInfoContainer, lv_pct(100));
    lv_obj_set_align(ui_VersionInfoContainer, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_VersionInfoContainer, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_VersionInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_VersionInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_VersionInfoContainer, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_VersionInfoContainer, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_VersionInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_VersionInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_VersionInfoContainer, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_VersionInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_VersionInfoLabel = lv_label_create(ui_VersionInfoContainer);
    lv_obj_set_width(ui_VersionInfoLabel, lv_pct(100));
    lv_obj_set_height(ui_VersionInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_VersionInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_VersionInfoLabel, "Version: unknown\nType: unknown\nHash: unknown");
    lv_obj_add_flag(ui_VersionInfoLabel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_VersionInfoLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DebugInfoContainer = lv_obj_create(ui_AboutBody);
    lv_obj_remove_style_all(ui_DebugInfoContainer);
    lv_obj_set_width(ui_DebugInfoContainer, lv_pct(100));
    lv_obj_set_height(ui_DebugInfoContainer, lv_pct(100));
    lv_obj_set_align(ui_DebugInfoContainer, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DebugInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_DebugInfoContainer, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DebugInfoContainer, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DebugInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DebugInfoContainer, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DebugInfoLabel = lv_label_create(ui_DebugInfoContainer);
    lv_obj_set_width(ui_DebugInfoLabel, lv_pct(100));
    lv_obj_set_height(ui_DebugInfoLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DebugInfoLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DebugInfoLabel, "Battery: unknown");
    lv_obj_add_flag(ui_DebugInfoLabel, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DebugInfoLabel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_AboutFooter = lv_obj_create(ui_AboutContent);
    lv_obj_remove_style_all(ui_AboutFooter);
    lv_obj_set_width(ui_AboutFooter, lv_pct(100));
    lv_obj_set_height(ui_AboutFooter, lv_pct(25));
    lv_obj_set_align(ui_AboutFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_AboutFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_AboutFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_AboutFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_AboutFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_AboutFooter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutMainActionButton = lv_btn_create(ui_AboutFooter);
    lv_obj_set_width(ui_AboutMainActionButton, 60);
    lv_obj_set_height(ui_AboutMainActionButton, 42);
    lv_obj_set_align(ui_AboutMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AboutMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AboutMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_AboutMainActionButton, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AboutMainActionButtonLabel = lv_label_create(ui_AboutMainActionButton);
    lv_obj_set_width(ui_AboutMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_AboutMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AboutMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_AboutMainActionButtonLabel, "Back");

    ui_UpdateButton = lv_btn_create(ui_AboutFooter);
    lv_obj_set_width(ui_UpdateButton, 60);
    lv_obj_set_height(ui_UpdateButton, 42);
    lv_obj_set_align(ui_UpdateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_UpdateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_UpdateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_UpdateButton, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_UpdateButtonLabel = lv_label_create(ui_UpdateButton);
    lv_obj_set_width(ui_UpdateButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_UpdateButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_UpdateButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_UpdateButtonLabel, "Update");

    lv_obj_add_event_cb(ui_AboutMainActionButton, ui_event_AboutMainActionButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_UpdateButton, ui_event_UpdateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AboutScreen, ui_event_AboutScreen, LV_EVENT_ALL, NULL);

}

void ui_AboutScreen_screen_destroy(void)
{
    if(ui_AboutScreen) lv_obj_del(ui_AboutScreen);

    // NULL screen variables
    ui_AboutScreen = NULL;
    ui_AboutContent = NULL;
    ui_AboutHeader = NULL;
    ui_AboutBody = NULL;
    ui_VersionInfoContainer = NULL;
    ui_VersionInfoLabel = NULL;
    ui_DebugInfoContainer = NULL;
    ui_DebugInfoLabel = NULL;
    ui_AboutFooter = NULL;
    ui_AboutMainActionButton = NULL;
    ui_AboutMainActionButtonLabel = NULL;
    ui_UpdateButton = NULL;
    ui_UpdateButtonLabel = NULL;

}
