// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_BMSSCREEN_H
#define UI_BMSSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_BMSScreen
extern void ui_BMSScreen_screen_init(void);
extern void ui_BMSScreen_screen_destroy(void);
extern void ui_event_BMSScreen(lv_event_t * e);
extern lv_obj_t * ui_BMSScreen;
extern lv_obj_t * ui_BMSContent;
extern lv_obj_t * ui_BMSHeader;
extern lv_obj_t * ui_BMSHeaderLabel;
extern lv_obj_t * ui_BMSBody;
extern lv_obj_t * ui_BMSGroupHeadingLabel;
extern lv_obj_t * ui_BMSDataBar;
extern lv_obj_t * ui_BMSDataValueBar;
extern lv_obj_t * ui_BMSDataValueLabel;
extern lv_obj_t * ui_BMSFooter;
extern void ui_event_BMSMainActionButton(lv_event_t * e);
extern lv_obj_t * ui_BMSMainActionButton;
extern lv_obj_t * ui_BMSMainActionButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

