// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: PubRemote

#include "ui.h"

lv_obj_t *ui_ChargeScreen = NULL;
lv_obj_t *ui_ChargeLevelDial = NULL;
lv_obj_t *ui_ChargeInfoContainer = NULL;
lv_obj_t *ui_ChargeInfoPrimaryLabel = NULL;
lv_obj_t *ui_ChargeInfoLevelLabel = NULL;
// event funtions
void ui_event_ChargeScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_SCREEN_LOAD_START) {
    charge_screen_load_start(e);
  }
  if (event_code == LV_EVENT_SCREEN_LOADED) {
    charge_screen_loaded(e);
  }
  if (event_code == LV_EVENT_SCREEN_UNLOAD_START) {
    charge_screen_unload_start(e);
  }
}

// build funtions

void ui_ChargeScreen_screen_init(void) {
  ui_ChargeScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_ChargeScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_add_event_cb(ui_ChargeScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                      ui_ChargeScreen_screen_destroy);
  lv_obj_set_style_bg_color(ui_ChargeScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ChargeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_ChargeScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_ChargeScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ChargeLevelDial = lv_arc_create(ui_ChargeScreen);
  lv_obj_set_width(ui_ChargeLevelDial, 240);
  lv_obj_set_height(ui_ChargeLevelDial, 240);
  lv_obj_set_align(ui_ChargeLevelDial, LV_ALIGN_CENTER);
  lv_arc_set_value(ui_ChargeLevelDial, 0);
  lv_arc_set_bg_angles(ui_ChargeLevelDial, 90, 89);
  lv_obj_set_style_arc_width(ui_ChargeLevelDial, 20, LV_PART_MAIN | LV_STATE_DEFAULT);

  lv_obj_set_style_arc_width(ui_ChargeLevelDial, 20, LV_PART_INDICATOR | LV_STATE_DEFAULT);

  lv_obj_set_style_bg_color(ui_ChargeLevelDial, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_ChargeLevelDial, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

  ui_ChargeInfoContainer = lv_obj_create(ui_ChargeScreen);
  lv_obj_remove_style_all(ui_ChargeInfoContainer);
  lv_obj_set_width(ui_ChargeInfoContainer, LV_SIZE_CONTENT);  /// 100
  lv_obj_set_height(ui_ChargeInfoContainer, LV_SIZE_CONTENT); /// 50
  lv_obj_set_align(ui_ChargeInfoContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_ChargeInfoContainer, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_ChargeInfoContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_remove_flag(ui_ChargeInfoContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_ChargeInfoPrimaryLabel = lv_label_create(ui_ChargeInfoContainer);
  lv_obj_set_width(ui_ChargeInfoPrimaryLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_ChargeInfoPrimaryLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_ChargeInfoPrimaryLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ChargeInfoPrimaryLabel, "Charging");
  lv_obj_set_style_text_align(ui_ChargeInfoPrimaryLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_font(ui_ChargeInfoPrimaryLabel, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_ChargeInfoLevelLabel = lv_label_create(ui_ChargeInfoContainer);
  lv_obj_set_width(ui_ChargeInfoLevelLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_ChargeInfoLevelLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_ChargeInfoLevelLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_ChargeInfoLevelLabel, "0%");

  lv_obj_add_event_cb(ui_ChargeScreen, ui_event_ChargeScreen, LV_EVENT_ALL, NULL);
}

void ui_ChargeScreen_screen_destroy(void) {
  if (ui_ChargeScreen)
    lv_obj_del(ui_ChargeScreen);

  // NULL screen variables
  ui_ChargeScreen = NULL;
  ui_ChargeLevelDial = NULL;
  ui_ChargeInfoContainer = NULL;
  ui_ChargeInfoPrimaryLabel = NULL;
  ui_ChargeInfoLevelLabel = NULL;
}
