// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: PubRemote

#ifndef UI_CALIBRATIONSCREEN_H
#define UI_CALIBRATIONSCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

  // SCREEN: ui_CalibrationScreen
  extern void ui_CalibrationScreen_screen_init(void);
  extern void ui_CalibrationScreen_screen_destroy(void);
  extern void ui_event_CalibrationScreen(lv_event_t *e);
  extern lv_obj_t *ui_CalibrationScreen;
  extern lv_obj_t *ui_CalibrationContent;
  extern lv_obj_t *ui_CalibrationHeader;
  extern lv_obj_t *ui_CalibrationHeaderLabel;
  extern lv_obj_t *ui_CalibrationBody;
  extern lv_obj_t *ui_CalibrationStepContent;
  extern void ui_event_ExpoSlider(lv_event_t *e);
  extern lv_obj_t *ui_ExpoSlider;
  extern lv_obj_t *ui_StickFlags;
  extern lv_obj_t *ui_InvertXContainer;
  extern lv_obj_t *ui_InvertXSwitch;
  extern lv_obj_t *ui_InvertXLabel;
  extern lv_obj_t *ui_InvertYContainer;
  extern lv_obj_t *ui_InvertYSwitch;
  extern lv_obj_t *ui_InvertYLabel;
  extern lv_obj_t *ui_InvertXYContainer;
  extern lv_obj_t *ui_InvertXYSwitch;
  extern lv_obj_t *ui_InvertXYLabel;
  extern lv_obj_t *ui_CalibrationIndicatorContainer;
  extern lv_obj_t *ui_DeadbandIndicator;
  extern lv_obj_t *ui_CalibrationLineVert;
  extern lv_obj_t *ui_CalibrationLineHoriz;
  extern lv_obj_t *ui_PositionIndicatorContainer;
  extern lv_obj_t *ui_PositionIndicatorHoriz;
  extern lv_obj_t *ui_PositionIndicatorVert;
  extern lv_obj_t *ui_CalibrationStepLabel;
  extern lv_obj_t *ui_CalibrationFooter;
  extern void ui_event_CalibrationSecondaryActionButton(lv_event_t *e);
  extern lv_obj_t *ui_CalibrationSecondaryActionButton;
  extern lv_obj_t *ui_CalibrationSecondaryActionButtonLabel;
  extern void ui_event_CalibrationPrimaryActionButton(lv_event_t *e);
  extern lv_obj_t *ui_CalibrationPrimaryActionButton;
  extern lv_obj_t *ui_CalibrationPrimaryActionButtonLabel;
  // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
