// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: PubRemote

#include "ui.h"

lv_obj_t *ui_CalibrationScreen = NULL;
lv_obj_t *ui_CalibrationContent = NULL;
lv_obj_t *ui_CalibrationHeader = NULL;
lv_obj_t *ui_CalibrationHeaderLabel = NULL;
lv_obj_t *ui_CalibrationBody = NULL;
lv_obj_t *ui_CalibrationStepContent = NULL;
lv_obj_t *ui_ExpoSlider = NULL;
lv_obj_t *ui_StickFlags = NULL;
lv_obj_t *ui_InvertXContainer = NULL;
lv_obj_t *ui_InvertXSwitch = NULL;
lv_obj_t *ui_InvertXLabel = NULL;
lv_obj_t *ui_InvertYContainer = NULL;
lv_obj_t *ui_InvertYSwitch = NULL;
lv_obj_t *ui_InvertYLabel = NULL;
lv_obj_t *ui_InvertXYContainer = NULL;
lv_obj_t *ui_InvertXYSwitch = NULL;
lv_obj_t *ui_InvertXYLabel = NULL;
lv_obj_t *ui_CalibrationIndicatorContainer = NULL;
lv_obj_t *ui_DeadbandIndicator = NULL;
lv_obj_t *ui_CalibrationLineVert = NULL;
lv_obj_t *ui_CalibrationLineHoriz = NULL;
lv_obj_t *ui_PositionIndicatorContainer = NULL;
lv_obj_t *ui_PositionIndicatorHoriz = NULL;
lv_obj_t *ui_PositionIndicatorVert = NULL;
lv_obj_t *ui_CalibrationStepLabel = NULL;
lv_obj_t *ui_CalibrationFooter = NULL;
lv_obj_t *ui_CalibrationSecondaryActionButton = NULL;
lv_obj_t *ui_CalibrationSecondaryActionButtonLabel = NULL;
lv_obj_t *ui_CalibrationPrimaryActionButton = NULL;
lv_obj_t *ui_CalibrationPrimaryActionButtonLabel = NULL;
// event funtions
void ui_event_CalibrationScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_SCREEN_LOADED) {
    calibration_screen_loaded(e);
  }
  if (event_code == LV_EVENT_SCREEN_UNLOAD_START) {
    calibration_screen_unload_start(e);
  }
  if (event_code == LV_EVENT_SCREEN_LOAD_START) {
    calibration_screen_load_start(e);
  }
}

void ui_event_ExpoSlider(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_VALUE_CHANGED) {
    expo_slider_change(e);
  }
}

void ui_event_CalibrationSecondaryActionButton(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MenuScreen_screen_init);
    calibration_settings_secondary_button_press(e);
  }
}

void ui_event_CalibrationPrimaryActionButton(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    calibration_settings_primary_button_press(e);
  }
}

// build funtions

void ui_CalibrationScreen_screen_init(void) {
  ui_CalibrationScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_CalibrationScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_add_event_cb(ui_CalibrationScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                      ui_CalibrationScreen_screen_destroy);
  lv_obj_set_style_bg_color(ui_CalibrationScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_CalibrationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_color(ui_CalibrationScreen, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_text_opa(ui_CalibrationScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationContent = lv_obj_create(ui_CalibrationScreen);
  lv_obj_remove_style_all(ui_CalibrationContent);
  lv_obj_set_width(ui_CalibrationContent, lv_pct(100));
  lv_obj_set_height(ui_CalibrationContent, lv_pct(100));
  lv_obj_set_align(ui_CalibrationContent, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_CalibrationContent, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_CalibrationContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_remove_flag(ui_CalibrationContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_text_font(ui_CalibrationContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationHeader = lv_obj_create(ui_CalibrationContent);
  lv_obj_remove_style_all(ui_CalibrationHeader);
  lv_obj_set_width(ui_CalibrationHeader, lv_pct(100));
  lv_obj_set_height(ui_CalibrationHeader, lv_pct(20));
  lv_obj_set_align(ui_CalibrationHeader, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_CalibrationHeader, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_CalibrationHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_remove_flag(ui_CalibrationHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_CalibrationHeaderLabel = lv_label_create(ui_CalibrationHeader);
  lv_obj_set_width(ui_CalibrationHeaderLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_CalibrationHeaderLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_CalibrationHeaderLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_CalibrationHeaderLabel, "X: 0.0 | Y: 0.0");
  lv_obj_set_style_text_font(ui_CalibrationHeaderLabel, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationBody = lv_obj_create(ui_CalibrationContent);
  lv_obj_remove_style_all(ui_CalibrationBody);
  lv_obj_set_width(ui_CalibrationBody, lv_pct(100));
  lv_obj_set_height(ui_CalibrationBody, lv_pct(55));
  lv_obj_set_align(ui_CalibrationBody, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_CalibrationBody, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_CalibrationBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(ui_CalibrationBody, LV_OBJ_FLAG_OVERFLOW_VISIBLE);                      /// Flags
  lv_obj_remove_flag(ui_CalibrationBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_row(ui_CalibrationBody, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_CalibrationBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationStepContent = lv_obj_create(ui_CalibrationBody);
  lv_obj_remove_style_all(ui_CalibrationStepContent);
  lv_obj_set_width(ui_CalibrationStepContent, lv_pct(100));
  lv_obj_set_height(ui_CalibrationStepContent, lv_pct(90));
  lv_obj_set_align(ui_CalibrationStepContent, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_CalibrationStepContent, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_CalibrationStepContent, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(ui_CalibrationStepContent, LV_OBJ_FLAG_OVERFLOW_VISIBLE);                      /// Flags
  lv_obj_remove_flag(ui_CalibrationStepContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_ExpoSlider = lv_slider_create(ui_CalibrationStepContent);
  lv_slider_set_range(ui_ExpoSlider, 1, 20);
  lv_slider_set_value(ui_ExpoSlider, 10, LV_ANIM_OFF);
  if (lv_slider_get_mode(ui_ExpoSlider) == LV_SLIDER_MODE_RANGE)
    lv_slider_set_left_value(ui_ExpoSlider, 0, LV_ANIM_OFF);
  lv_obj_set_height(ui_ExpoSlider, 15);
  lv_obj_set_width(ui_ExpoSlider, lv_pct(75));
  lv_obj_set_align(ui_ExpoSlider, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_ExpoSlider, LV_OBJ_FLAG_HIDDEN); /// Flags

  // Compensating for LVGL9.1 draw crash with bar/slider max value when top-padding is nonzero and right-padding is 0
  if (lv_obj_get_style_pad_top(ui_ExpoSlider, LV_PART_MAIN) > 0)
    lv_obj_set_style_pad_right(ui_ExpoSlider, lv_obj_get_style_pad_right(ui_ExpoSlider, LV_PART_MAIN) + 1,
                               LV_PART_MAIN);
  ui_StickFlags = lv_obj_create(ui_CalibrationStepContent);
  lv_obj_remove_style_all(ui_StickFlags);
  lv_obj_set_width(ui_StickFlags, lv_pct(100));
  lv_obj_set_height(ui_StickFlags, lv_pct(100));
  lv_obj_set_align(ui_StickFlags, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_StickFlags, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_StickFlags, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(ui_StickFlags, LV_OBJ_FLAG_HIDDEN);                                /// Flags
  lv_obj_remove_flag(ui_StickFlags, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_row(ui_StickFlags, 8, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_StickFlags, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_InvertXContainer = lv_obj_create(ui_StickFlags);
  lv_obj_remove_style_all(ui_InvertXContainer);
  lv_obj_set_width(ui_InvertXContainer, lv_pct(50));
  lv_obj_set_height(ui_InvertXContainer, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertXContainer, 9);
  lv_obj_set_y(ui_InvertXContainer, -74);
  lv_obj_set_align(ui_InvertXContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_InvertXContainer, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_InvertXContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(ui_InvertXContainer, LV_OBJ_FLAG_HIDDEN);                                /// Flags
  lv_obj_remove_flag(ui_InvertXContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_InvertXSwitch = lv_switch_create(ui_InvertXContainer);
  lv_obj_set_height(ui_InvertXSwitch, 25);
  lv_obj_set_width(ui_InvertXSwitch, lv_pct(50));
  lv_obj_set_x(ui_InvertXSwitch, 12);
  lv_obj_set_y(ui_InvertXSwitch, -10);
  lv_obj_set_align(ui_InvertXSwitch, LV_ALIGN_CENTER);

  ui_InvertXLabel = lv_label_create(ui_InvertXContainer);
  lv_obj_set_width(ui_InvertXLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_InvertXLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertXLabel, 6);
  lv_obj_set_y(ui_InvertXLabel, -17);
  lv_obj_set_align(ui_InvertXLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_InvertXLabel, "Invert X");

  ui_InvertYContainer = lv_obj_create(ui_StickFlags);
  lv_obj_remove_style_all(ui_InvertYContainer);
  lv_obj_set_width(ui_InvertYContainer, lv_pct(50));
  lv_obj_set_height(ui_InvertYContainer, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertYContainer, 9);
  lv_obj_set_y(ui_InvertYContainer, -74);
  lv_obj_set_align(ui_InvertYContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_InvertYContainer, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_InvertYContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_remove_flag(ui_InvertYContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_InvertYSwitch = lv_switch_create(ui_InvertYContainer);
  lv_obj_set_height(ui_InvertYSwitch, 25);
  lv_obj_set_width(ui_InvertYSwitch, lv_pct(50));
  lv_obj_set_x(ui_InvertYSwitch, 12);
  lv_obj_set_y(ui_InvertYSwitch, -10);
  lv_obj_set_align(ui_InvertYSwitch, LV_ALIGN_CENTER);

  ui_InvertYLabel = lv_label_create(ui_InvertYContainer);
  lv_obj_set_width(ui_InvertYLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_InvertYLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertYLabel, 6);
  lv_obj_set_y(ui_InvertYLabel, -17);
  lv_obj_set_align(ui_InvertYLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_InvertYLabel, "Invert Y");

  ui_InvertXYContainer = lv_obj_create(ui_StickFlags);
  lv_obj_remove_style_all(ui_InvertXYContainer);
  lv_obj_set_width(ui_InvertXYContainer, lv_pct(50));
  lv_obj_set_height(ui_InvertXYContainer, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertXYContainer, 9);
  lv_obj_set_y(ui_InvertXYContainer, -74);
  lv_obj_set_align(ui_InvertXYContainer, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_InvertXYContainer, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_InvertXYContainer, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_add_flag(ui_InvertXYContainer, LV_OBJ_FLAG_HIDDEN);                                /// Flags
  lv_obj_remove_flag(ui_InvertXYContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_InvertXYSwitch = lv_switch_create(ui_InvertXYContainer);
  lv_obj_set_height(ui_InvertXYSwitch, 25);
  lv_obj_set_width(ui_InvertXYSwitch, lv_pct(50));
  lv_obj_set_x(ui_InvertXYSwitch, 12);
  lv_obj_set_y(ui_InvertXYSwitch, -10);
  lv_obj_set_align(ui_InvertXYSwitch, LV_ALIGN_CENTER);

  ui_InvertXYLabel = lv_label_create(ui_InvertXYContainer);
  lv_obj_set_width(ui_InvertXYLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_InvertXYLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_InvertXYLabel, 6);
  lv_obj_set_y(ui_InvertXYLabel, -17);
  lv_obj_set_align(ui_InvertXYLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_InvertXYLabel, "Invert XY");

  ui_CalibrationIndicatorContainer = lv_obj_create(ui_CalibrationStepContent);
  lv_obj_remove_style_all(ui_CalibrationIndicatorContainer);
  lv_obj_set_width(ui_CalibrationIndicatorContainer, 80);
  lv_obj_set_height(ui_CalibrationIndicatorContainer, 80);
  lv_obj_set_align(ui_CalibrationIndicatorContainer, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_CalibrationIndicatorContainer, LV_OBJ_FLAG_OVERFLOW_VISIBLE);                      /// Flags
  lv_obj_remove_flag(ui_CalibrationIndicatorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_CalibrationIndicatorContainer, 999, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_CalibrationIndicatorContainer, lv_color_hex(0x414141),
                                LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_CalibrationIndicatorContainer, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_CalibrationIndicatorContainer, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_side(ui_CalibrationIndicatorContainer, LV_BORDER_SIDE_FULL, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_DeadbandIndicator = lv_obj_create(ui_CalibrationIndicatorContainer);
  lv_obj_remove_style_all(ui_DeadbandIndicator);
  lv_obj_set_width(ui_DeadbandIndicator, lv_pct(50));
  lv_obj_set_height(ui_DeadbandIndicator, lv_pct(50));
  lv_obj_set_align(ui_DeadbandIndicator, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_DeadbandIndicator, LV_OBJ_FLAG_HIDDEN);                                /// Flags
  lv_obj_remove_flag(ui_DeadbandIndicator, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_radius(ui_DeadbandIndicator, 999, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_color(ui_DeadbandIndicator, lv_color_hex(0x414141), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_opa(ui_DeadbandIndicator, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_border_width(ui_DeadbandIndicator, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationLineVert = lv_obj_create(ui_CalibrationIndicatorContainer);
  lv_obj_remove_style_all(ui_CalibrationLineVert);
  lv_obj_set_width(ui_CalibrationLineVert, 4);
  lv_obj_set_height(ui_CalibrationLineVert, lv_pct(130));
  lv_obj_set_align(ui_CalibrationLineVert, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_CalibrationLineVert, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_CalibrationLineVert, lv_color_hex(0xEE4266), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_CalibrationLineVert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationLineHoriz = lv_obj_create(ui_CalibrationIndicatorContainer);
  lv_obj_remove_style_all(ui_CalibrationLineHoriz);
  lv_obj_set_height(ui_CalibrationLineHoriz, 4);
  lv_obj_set_width(ui_CalibrationLineHoriz, lv_pct(130));
  lv_obj_set_align(ui_CalibrationLineHoriz, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_CalibrationLineHoriz, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_CalibrationLineHoriz, lv_color_hex(0xEE4266), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_CalibrationLineHoriz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PositionIndicatorContainer = lv_obj_create(ui_CalibrationIndicatorContainer);
  lv_obj_remove_style_all(ui_PositionIndicatorContainer);
  lv_obj_set_width(ui_PositionIndicatorContainer, lv_pct(20));
  lv_obj_set_height(ui_PositionIndicatorContainer, lv_pct(20));
  lv_obj_set_align(ui_PositionIndicatorContainer, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_PositionIndicatorContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags

  ui_PositionIndicatorHoriz = lv_obj_create(ui_PositionIndicatorContainer);
  lv_obj_remove_style_all(ui_PositionIndicatorHoriz);
  lv_obj_set_height(ui_PositionIndicatorHoriz, 4);
  lv_obj_set_width(ui_PositionIndicatorHoriz, lv_pct(100));
  lv_obj_set_align(ui_PositionIndicatorHoriz, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_PositionIndicatorHoriz, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_PositionIndicatorHoriz, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PositionIndicatorHoriz, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_PositionIndicatorVert = lv_obj_create(ui_PositionIndicatorContainer);
  lv_obj_remove_style_all(ui_PositionIndicatorVert);
  lv_obj_set_width(ui_PositionIndicatorVert, 4);
  lv_obj_set_height(ui_PositionIndicatorVert, lv_pct(100));
  lv_obj_set_align(ui_PositionIndicatorVert, LV_ALIGN_CENTER);
  lv_obj_remove_flag(ui_PositionIndicatorVert, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_bg_color(ui_PositionIndicatorVert, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_PositionIndicatorVert, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationStepLabel = lv_label_create(ui_CalibrationBody);
  lv_obj_set_width(ui_CalibrationStepLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_CalibrationStepLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_CalibrationStepLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_CalibrationStepLabel, "Press start to begin calibration");
  lv_obj_set_style_text_font(ui_CalibrationStepLabel, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_left(ui_CalibrationStepLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_CalibrationStepLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_CalibrationStepLabel, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_CalibrationStepLabel, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationFooter = lv_obj_create(ui_CalibrationContent);
  lv_obj_remove_style_all(ui_CalibrationFooter);
  lv_obj_set_width(ui_CalibrationFooter, lv_pct(100));
  lv_obj_set_height(ui_CalibrationFooter, lv_pct(25));
  lv_obj_set_align(ui_CalibrationFooter, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_CalibrationFooter, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_CalibrationFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_remove_flag(ui_CalibrationFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_row(ui_CalibrationFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_CalibrationFooter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationSecondaryActionButton = lv_button_create(ui_CalibrationFooter);
  lv_obj_set_width(ui_CalibrationSecondaryActionButton, 60);
  lv_obj_set_height(ui_CalibrationSecondaryActionButton, 42);
  lv_obj_set_align(ui_CalibrationSecondaryActionButton, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_CalibrationSecondaryActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_remove_flag(ui_CalibrationSecondaryActionButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_text_font(ui_CalibrationSecondaryActionButton, &ui_font_Inter_Bold_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationSecondaryActionButtonLabel = lv_label_create(ui_CalibrationSecondaryActionButton);
  lv_obj_set_width(ui_CalibrationSecondaryActionButtonLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_CalibrationSecondaryActionButtonLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_CalibrationSecondaryActionButtonLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_CalibrationSecondaryActionButtonLabel, "Cancel");

  ui_CalibrationPrimaryActionButton = lv_button_create(ui_CalibrationFooter);
  lv_obj_set_width(ui_CalibrationPrimaryActionButton, 60);
  lv_obj_set_height(ui_CalibrationPrimaryActionButton, 42);
  lv_obj_set_align(ui_CalibrationPrimaryActionButton, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_CalibrationPrimaryActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_remove_flag(ui_CalibrationPrimaryActionButton, LV_OBJ_FLAG_SCROLLABLE);   /// Flags
  lv_obj_set_style_text_font(ui_CalibrationPrimaryActionButton, &ui_font_Inter_Bold_14,
                             LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_CalibrationPrimaryActionButtonLabel = lv_label_create(ui_CalibrationPrimaryActionButton);
  lv_obj_set_width(ui_CalibrationPrimaryActionButtonLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_CalibrationPrimaryActionButtonLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_CalibrationPrimaryActionButtonLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_CalibrationPrimaryActionButtonLabel, "Start");

  lv_obj_add_event_cb(ui_ExpoSlider, ui_event_ExpoSlider, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_CalibrationSecondaryActionButton, ui_event_CalibrationSecondaryActionButton, LV_EVENT_ALL,
                      NULL);
  lv_obj_add_event_cb(ui_CalibrationPrimaryActionButton, ui_event_CalibrationPrimaryActionButton, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_CalibrationScreen, ui_event_CalibrationScreen, LV_EVENT_ALL, NULL);
}

void ui_CalibrationScreen_screen_destroy(void) {
  if (ui_CalibrationScreen)
    lv_obj_del(ui_CalibrationScreen);

  // NULL screen variables
  ui_CalibrationScreen = NULL;
  ui_CalibrationContent = NULL;
  ui_CalibrationHeader = NULL;
  ui_CalibrationHeaderLabel = NULL;
  ui_CalibrationBody = NULL;
  ui_CalibrationStepContent = NULL;
  ui_ExpoSlider = NULL;
  ui_StickFlags = NULL;
  ui_InvertXContainer = NULL;
  ui_InvertXSwitch = NULL;
  ui_InvertXLabel = NULL;
  ui_InvertYContainer = NULL;
  ui_InvertYSwitch = NULL;
  ui_InvertYLabel = NULL;
  ui_InvertXYContainer = NULL;
  ui_InvertXYSwitch = NULL;
  ui_InvertXYLabel = NULL;
  ui_CalibrationIndicatorContainer = NULL;
  ui_DeadbandIndicator = NULL;
  ui_CalibrationLineVert = NULL;
  ui_CalibrationLineHoriz = NULL;
  ui_PositionIndicatorContainer = NULL;
  ui_PositionIndicatorHoriz = NULL;
  ui_PositionIndicatorVert = NULL;
  ui_CalibrationStepLabel = NULL;
  ui_CalibrationFooter = NULL;
  ui_CalibrationSecondaryActionButton = NULL;
  ui_CalibrationSecondaryActionButtonLabel = NULL;
  ui_CalibrationPrimaryActionButton = NULL;
  ui_CalibrationPrimaryActionButtonLabel = NULL;
}
