// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_CHARGINGSCREEN_H
#define UI_CHARGINGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ChargingScreen
extern void ui_ChargingScreen_screen_init(void);
extern void ui_ChargingScreen_screen_destroy(void);
extern lv_obj_t * ui_ChargingScreen;
extern lv_obj_t * ui_ChargeLevelDial;
extern lv_obj_t * ui_ChargeInfoContainer;
extern lv_obj_t * ui_ChargeInfoPrimaryLabel;
extern lv_obj_t * ui_ChargeInfoLevelLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

