// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_MenuContent = NULL;
lv_obj_t * ui_MenuBody = NULL;
// event funtions
void ui_event_MenuScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        menu_screen_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        menu_screen_unload_start(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        menu_screen_load_start(e);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuContent = lv_obj_create(ui_MenuScreen);
    lv_obj_remove_style_all(ui_MenuContent);
    lv_obj_set_width(ui_MenuContent, lv_pct(100));
    lv_obj_set_height(ui_MenuContent, lv_pct(100));
    lv_obj_set_align(ui_MenuContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MenuContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MenuContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuBody = lv_obj_create(ui_MenuContent);
    lv_obj_remove_style_all(ui_MenuBody);
    lv_obj_set_width(ui_MenuBody, lv_pct(100));
    lv_obj_set_height(ui_MenuBody, lv_pct(100));
    lv_obj_set_align(ui_MenuBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MenuBody, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MenuBody, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_MenuBody, LV_DIR_VER);
    lv_obj_set_style_pad_left(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MenuBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MenuBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuBody, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_MenuScreen, ui_event_MenuScreen, LV_EVENT_ALL, NULL);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_MenuContent = NULL;
    ui_MenuBody = NULL;

}
