// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_MENUSCREEN_H
#define UI_MENUSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MenuScreen
extern void ui_MenuScreen_screen_init(void);
extern void ui_MenuScreen_screen_destroy(void);
extern void ui_event_MenuScreen(lv_event_t * e);
extern lv_obj_t * ui_MenuScreen;
extern lv_obj_t * ui_MenuContent;
extern lv_obj_t * ui_MenuBody;
extern void ui_event_MenuBackButton(lv_event_t * e);
extern lv_obj_t * ui_MenuBackButton;
extern lv_obj_t * ui_MenuBackButtonLabel;
extern void ui_event_MenuConnectButton(lv_event_t * e);
extern lv_obj_t * ui_MenuConnectButton;
extern lv_obj_t * ui_MenuConnectButtonLabel;
extern void ui_event_MenuPocketModeButton(lv_event_t * e);
extern lv_obj_t * ui_MenuPocketModeButton;
extern lv_obj_t * ui_MenuPocketModeButtonLabel;
extern void ui_event_MenuSettingsButton(lv_event_t * e);
extern lv_obj_t * ui_MenuSettingsButton;
extern lv_obj_t * ui_MenuSettingsButtonLabel;
extern void ui_event_MenuCalibrateButton(lv_event_t * e);
extern lv_obj_t * ui_MenuCalibrateButton;
extern lv_obj_t * ui_MenuCalibrateButtonLabel;
extern void ui_event_MenuPairButton(lv_event_t * e);
extern lv_obj_t * ui_MenuPairButton;
extern lv_obj_t * ui_MenuPairButtonLabel;
extern void ui_event_MenuAboutButton(lv_event_t * e);
extern lv_obj_t * ui_MenuAboutButton;
extern lv_obj_t * ui_MenuAboutButtonLabel;
extern void ui_event_MenuShutdownButton(lv_event_t * e);
extern lv_obj_t * ui_MenuShutdownButton;
extern lv_obj_t * ui_MenuShutdownButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

