// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

lv_obj_t * ui_MenuScreen = NULL;
lv_obj_t * ui_MenuContent = NULL;
lv_obj_t * ui_MenuBody = NULL;
lv_obj_t * ui_MenuBackButton = NULL;
lv_obj_t * ui_MenuBackButtonLabel = NULL;
lv_obj_t * ui_MenuConnectButton = NULL;
lv_obj_t * ui_MenuConnectButtonLabel = NULL;
lv_obj_t * ui_MenuPocketModeButton = NULL;
lv_obj_t * ui_MenuPocketModeButtonLabel = NULL;
lv_obj_t * ui_MenuSettingsButton = NULL;
lv_obj_t * ui_MenuSettingsButtonLabel = NULL;
lv_obj_t * ui_MenuCalibrateButton = NULL;
lv_obj_t * ui_MenuCalibrateButtonLabel = NULL;
lv_obj_t * ui_MenuPairButton = NULL;
lv_obj_t * ui_MenuPairButtonLabel = NULL;
lv_obj_t * ui_MenuAboutButton = NULL;
lv_obj_t * ui_MenuAboutButtonLabel = NULL;
lv_obj_t * ui_MenuShutdownButton = NULL;
lv_obj_t * ui_MenuShutdownButtonLabel = NULL;
// event funtions
void ui_event_MenuScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        menu_screen_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOAD_START) {
        menu_screen_unload_start(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        menu_screen_load_start(e);
    }
}

void ui_event_MenuBackButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_StatsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_StatsScreen_screen_init);
    }
}

void ui_event_MenuConnectButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        menu_connect_press(e);
    }
}

void ui_event_MenuPocketModeButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        menu_pocket_mode_press(e);
    }
}

void ui_event_MenuSettingsButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SettingsScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_SettingsScreen_screen_init);
    }
}

void ui_event_MenuCalibrateButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_CalibrationScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_CalibrationScreen_screen_init);
    }
}

void ui_event_MenuPairButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_PairingScreen, LV_SCR_LOAD_ANIM_MOVE_LEFT, 200, 0, &ui_PairingScreen_screen_init);
    }
}

void ui_event_MenuAboutButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_AboutScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, &ui_AboutScreen_screen_init);
    }
}

void ui_event_MenuShutdownButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        shutdown_button_press(e);
    }
    if(event_code == LV_EVENT_LONG_PRESSED) {
        shutdown_button_long_press(e);
    }
    if(event_code == LV_EVENT_PRESSED) {
        shutdown_button_down(e);
    }
}

// build funtions

void ui_MenuScreen_screen_init(void)
{
    ui_MenuScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_MenuScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MenuScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_MenuScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuContent = lv_obj_create(ui_MenuScreen);
    lv_obj_remove_style_all(ui_MenuContent);
    lv_obj_set_width(ui_MenuContent, lv_pct(100));
    lv_obj_set_height(ui_MenuContent, lv_pct(100));
    lv_obj_set_align(ui_MenuContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MenuContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_MenuContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuBody = lv_obj_create(ui_MenuContent);
    lv_obj_remove_style_all(ui_MenuBody);
    lv_obj_set_width(ui_MenuBody, lv_pct(100));
    lv_obj_set_height(ui_MenuBody, lv_pct(100));
    lv_obj_set_align(ui_MenuBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_MenuBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_MenuBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_MenuBody, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE |
                      LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_MenuBody, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_MenuBody, LV_DIR_VER);
    lv_obj_set_style_pad_left(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_MenuBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_MenuBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_MenuBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_MenuBody, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_MenuBackButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuBackButton, 42);
    lv_obj_set_width(ui_MenuBackButton, lv_pct(100));
    lv_obj_set_align(ui_MenuBackButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuBackButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuBackButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuBackButtonLabel = lv_label_create(ui_MenuBackButton);
    lv_obj_set_width(ui_MenuBackButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuBackButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuBackButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuBackButtonLabel, "Back");

    ui_MenuConnectButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuConnectButton, 42);
    lv_obj_set_width(ui_MenuConnectButton, lv_pct(100));
    lv_obj_set_align(ui_MenuConnectButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuConnectButton, LV_OBJ_FLAG_HIDDEN | LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuConnectButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuConnectButtonLabel = lv_label_create(ui_MenuConnectButton);
    lv_obj_set_width(ui_MenuConnectButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuConnectButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuConnectButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuConnectButtonLabel, "Connect");

    ui_MenuPocketModeButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuPocketModeButton, 42);
    lv_obj_set_width(ui_MenuPocketModeButton, lv_pct(100));
    lv_obj_set_align(ui_MenuPocketModeButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuPocketModeButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuPocketModeButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuPocketModeButtonLabel = lv_label_create(ui_MenuPocketModeButton);
    lv_obj_set_width(ui_MenuPocketModeButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuPocketModeButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuPocketModeButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuPocketModeButtonLabel, "Enable Pocket Mode");

    ui_MenuSettingsButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuSettingsButton, 42);
    lv_obj_set_width(ui_MenuSettingsButton, lv_pct(100));
    lv_obj_set_align(ui_MenuSettingsButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuSettingsButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuSettingsButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuSettingsButtonLabel = lv_label_create(ui_MenuSettingsButton);
    lv_obj_set_width(ui_MenuSettingsButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuSettingsButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuSettingsButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuSettingsButtonLabel, "Settings");

    ui_MenuCalibrateButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuCalibrateButton, 42);
    lv_obj_set_width(ui_MenuCalibrateButton, lv_pct(100));
    lv_obj_set_align(ui_MenuCalibrateButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuCalibrateButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuCalibrateButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuCalibrateButtonLabel = lv_label_create(ui_MenuCalibrateButton);
    lv_obj_set_width(ui_MenuCalibrateButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuCalibrateButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuCalibrateButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuCalibrateButtonLabel, "Calibration");

    ui_MenuPairButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuPairButton, 42);
    lv_obj_set_width(ui_MenuPairButton, lv_pct(100));
    lv_obj_set_align(ui_MenuPairButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuPairButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuPairButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuPairButtonLabel = lv_label_create(ui_MenuPairButton);
    lv_obj_set_width(ui_MenuPairButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuPairButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuPairButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuPairButtonLabel, "Pairing");

    ui_MenuAboutButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuAboutButton, 42);
    lv_obj_set_width(ui_MenuAboutButton, lv_pct(100));
    lv_obj_set_align(ui_MenuAboutButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuAboutButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuAboutButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuAboutButtonLabel = lv_label_create(ui_MenuAboutButton);
    lv_obj_set_width(ui_MenuAboutButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuAboutButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuAboutButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuAboutButtonLabel, "About");

    ui_MenuShutdownButton = lv_btn_create(ui_MenuBody);
    lv_obj_set_height(ui_MenuShutdownButton, 42);
    lv_obj_set_width(ui_MenuShutdownButton, lv_pct(100));
    lv_obj_set_align(ui_MenuShutdownButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MenuShutdownButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_MenuShutdownButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_MenuShutdownButtonLabel = lv_label_create(ui_MenuShutdownButton);
    lv_obj_set_width(ui_MenuShutdownButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MenuShutdownButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_MenuShutdownButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MenuShutdownButtonLabel, "Shutdown");

    lv_obj_add_event_cb(ui_MenuBackButton, ui_event_MenuBackButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuConnectButton, ui_event_MenuConnectButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuPocketModeButton, ui_event_MenuPocketModeButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuSettingsButton, ui_event_MenuSettingsButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuCalibrateButton, ui_event_MenuCalibrateButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuPairButton, ui_event_MenuPairButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuAboutButton, ui_event_MenuAboutButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuShutdownButton, ui_event_MenuShutdownButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MenuScreen, ui_event_MenuScreen, LV_EVENT_ALL, NULL);

}

void ui_MenuScreen_screen_destroy(void)
{
    if(ui_MenuScreen) lv_obj_del(ui_MenuScreen);

    // NULL screen variables
    ui_MenuScreen = NULL;
    ui_MenuContent = NULL;
    ui_MenuBody = NULL;
    ui_MenuBackButton = NULL;
    ui_MenuBackButtonLabel = NULL;
    ui_MenuConnectButton = NULL;
    ui_MenuConnectButtonLabel = NULL;
    ui_MenuPocketModeButton = NULL;
    ui_MenuPocketModeButtonLabel = NULL;
    ui_MenuSettingsButton = NULL;
    ui_MenuSettingsButtonLabel = NULL;
    ui_MenuCalibrateButton = NULL;
    ui_MenuCalibrateButtonLabel = NULL;
    ui_MenuPairButton = NULL;
    ui_MenuPairButtonLabel = NULL;
    ui_MenuAboutButton = NULL;
    ui_MenuAboutButtonLabel = NULL;
    ui_MenuShutdownButton = NULL;
    ui_MenuShutdownButtonLabel = NULL;

}
