// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.2.2
// Project name: PubRemote

#include "ui.h"

lv_obj_t *ui_SplashScreen = NULL;
lv_obj_t *ui_SplashScreenLogo = NULL;
// event funtions
void ui_event_SplashScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_SCREEN_LOADED) {
    _ui_screen_change(&ui_StatsScreen, LV_SCR_LOAD_ANIM_FADE_ON, 200, 1000, &ui_StatsScreen_screen_init);
  }
}

// build funtions

void ui_SplashScreen_screen_init(void) {
  ui_SplashScreen = lv_obj_create(NULL);
  lv_obj_remove_flag(ui_SplashScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_add_event_cb(ui_SplashScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED,
                      ui_SplashScreen_screen_destroy);
  lv_obj_set_style_bg_color(ui_SplashScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_SplashScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_SplashScreenLogo = lv_image_create(ui_SplashScreen);
  lv_image_set_src(ui_SplashScreenLogo, &ui_img_icon2_png);
  lv_obj_set_width(ui_SplashScreenLogo, LV_SIZE_CONTENT);  /// 30
  lv_obj_set_height(ui_SplashScreenLogo, LV_SIZE_CONTENT); /// 30
  lv_obj_set_align(ui_SplashScreenLogo, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_SplashScreenLogo, LV_OBJ_FLAG_ADV_HITTEST);   /// Flags
  lv_obj_remove_flag(ui_SplashScreenLogo, LV_OBJ_FLAG_SCROLLABLE); /// Flags

  lv_obj_add_event_cb(ui_SplashScreen, ui_event_SplashScreen, LV_EVENT_ALL, NULL);
}

void ui_SplashScreen_screen_destroy(void) {
  if (ui_SplashScreen)
    lv_obj_del(ui_SplashScreen);

  // NULL screen variables
  ui_SplashScreen = NULL;
  ui_SplashScreenLogo = NULL;
}
