// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

lv_obj_t * ui_SettingsScreen = NULL;
lv_obj_t * ui_SettingsContent = NULL;
lv_obj_t * ui_SettingsHeader = NULL;
lv_obj_t * ui_SettingsBody = NULL;
lv_obj_t * ui_BrightnessBody = NULL;
lv_obj_t * ui_BrightnessSlider = NULL;
lv_obj_t * ui_BrightnessLabel = NULL;
lv_obj_t * ui_RotationBody = NULL;
lv_obj_t * ui_Rotation = NULL;
lv_obj_t * ui_RotationLabel = NULL;
lv_obj_t * ui_PowerBody = NULL;
lv_obj_t * ui_AutoOffTime = NULL;
lv_obj_t * ui_PowerLabel = NULL;
lv_obj_t * ui_TempUnitsBody = NULL;
lv_obj_t * ui_TempUnits = NULL;
lv_obj_t * ui_TempUnitsLabel = NULL;
lv_obj_t * ui_DistanceUnitsBody = NULL;
lv_obj_t * ui_DistanceUnits = NULL;
lv_obj_t * ui_DistanceUnitsLabel = NULL;
lv_obj_t * ui_StartupSoundBody = NULL;
lv_obj_t * ui_StartupSound = NULL;
lv_obj_t * ui_StartupSoundLabel = NULL;
lv_obj_t * ui_ThemeColorBody = NULL;
lv_obj_t * ui_ThemeColor = NULL;
lv_obj_t * ui_ThemeColorLabel = NULL;
lv_obj_t * ui_DarkTextBody = NULL;
lv_obj_t * ui_DarkText = NULL;
lv_obj_t * ui_DarkTextLabel = NULL;
lv_obj_t * ui_SettingsFooter = NULL;
lv_obj_t * ui_SettingsMainActionButton = NULL;
lv_obj_t * ui_SettingsMainActionButtonLabel = NULL;
// event funtions
void ui_event_SettingsScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_SCREEN_LOADED) {
        settings_screen_loaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_UNLOADED) {
        settings_screen_unloaded(e);
    }
    if(event_code == LV_EVENT_SCREEN_LOAD_START) {
        settings_screen_load_start(e);
    }
}

void ui_event_BrightnessSlider(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        brightness_slider_change(e);
    }
}

void ui_event_Rotation(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        screen_rotation_change(e);
    }
}

void ui_event_AutoOffTime(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        auto_off_select_change(e);
    }
}

void ui_event_TempUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        temp_units_select_change(e);
    }
}

void ui_event_DistanceUnits(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        distance_units_select_change(e);
    }
}

void ui_event_StartupSound(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        startup_sound_select_change(e);
    }
}

void ui_event_ThemeColor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        theme_color_picker_change(e);
    }
}

void ui_event_DarkText(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        dark_text_switch_change(e);
    }
}

void ui_event_SettingsMainActionButton(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MenuScreen_screen_init);
        settings_save(e);
    }
}

// build funtions

void ui_SettingsScreen_screen_init(void)
{
    ui_SettingsScreen = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_SettingsScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_add_event_cb(ui_SettingsScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_SettingsScreen);
    lv_obj_set_style_bg_color(ui_SettingsScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_SettingsScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsContent = lv_obj_create(ui_SettingsScreen);
    lv_obj_remove_style_all(ui_SettingsContent);
    lv_obj_set_width(ui_SettingsContent, lv_pct(100));
    lv_obj_set_height(ui_SettingsContent, lv_pct(100));
    lv_obj_set_align(ui_SettingsContent, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsContent, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_SettingsContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_SettingsContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsHeader = lv_obj_create(ui_SettingsContent);
    lv_obj_remove_style_all(ui_SettingsHeader);
    lv_obj_set_width(ui_SettingsHeader, lv_pct(100));
    lv_obj_set_height(ui_SettingsHeader, lv_pct(20));
    lv_obj_set_align(ui_SettingsHeader, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsHeader, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_left(ui_SettingsHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_SettingsHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_SettingsHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_SettingsHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_SettingsHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsHeader, 5, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsBody = lv_obj_create(ui_SettingsContent);
    lv_obj_remove_style_all(ui_SettingsBody);
    lv_obj_set_width(ui_SettingsBody, lv_pct(100));
    lv_obj_set_height(ui_SettingsBody, lv_pct(55));
    lv_obj_set_align(ui_SettingsBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsBody, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsBody, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsBody, LV_OBJ_FLAG_SCROLL_ONE);     /// Flags
    lv_obj_clear_flag(ui_SettingsBody, LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SCROLL_MOMENTUM);      /// Flags
    lv_obj_set_scrollbar_mode(ui_SettingsBody, LV_SCROLLBAR_MODE_ACTIVE);
    lv_obj_set_scroll_dir(ui_SettingsBody, LV_DIR_HOR);

    ui_BrightnessBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_BrightnessBody);
    lv_obj_set_width(ui_BrightnessBody, lv_pct(100));
    lv_obj_set_height(ui_BrightnessBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_BrightnessBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_BrightnessBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_BrightnessBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessBody, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_BrightnessBody,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_BrightnessBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_BrightnessBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_BrightnessBody, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_BrightnessBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_BrightnessSlider = lv_slider_create(ui_BrightnessBody);
    lv_slider_set_range(ui_BrightnessSlider, 10, 255);
    lv_slider_set_value(ui_BrightnessSlider, 0, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_BrightnessSlider) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_BrightnessSlider, 0,
                                                                                                     LV_ANIM_OFF);
    lv_obj_set_height(ui_BrightnessSlider, 15);
    lv_obj_set_width(ui_BrightnessSlider, lv_pct(100));
    lv_obj_set_align(ui_BrightnessSlider, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_BrightnessSlider, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_BrightnessLabel = lv_label_create(ui_BrightnessBody);
    lv_obj_set_width(ui_BrightnessLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessLabel, 19);
    lv_obj_set_y(ui_BrightnessLabel, 38);
    lv_obj_set_align(ui_BrightnessLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BrightnessLabel, "Screen brightness");

    ui_RotationBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_RotationBody);
    lv_obj_set_width(ui_RotationBody, lv_pct(100));
    lv_obj_set_height(ui_RotationBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_RotationBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_RotationBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_RotationBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_add_flag(ui_RotationBody, LV_OBJ_FLAG_OVERFLOW_VISIBLE);     /// Flags
    lv_obj_clear_flag(ui_RotationBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_RotationBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_RotationBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_RotationBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_RotationBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_RotationBody, 20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_RotationBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Rotation = lv_dropdown_create(ui_RotationBody);
    lv_dropdown_set_options(ui_Rotation, "None\n90 degrees\n180 degress\n270 degrees");
    lv_obj_set_width(ui_Rotation, lv_pct(100));
    lv_obj_set_height(ui_Rotation, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Rotation, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Rotation, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Rotation, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_Rotation, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_Rotation, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Rotation), &ui_font_Inter_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Rotation), &ui_font_Inter_14,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_RotationLabel = lv_label_create(ui_RotationBody);
    lv_obj_set_width(ui_RotationLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RotationLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RotationLabel, 19);
    lv_obj_set_y(ui_RotationLabel, 38);
    lv_obj_set_align(ui_RotationLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RotationLabel, "Screen rotation");

    ui_PowerBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_PowerBody);
    lv_obj_set_width(ui_PowerBody, lv_pct(100));
    lv_obj_set_height(ui_PowerBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_PowerBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_PowerBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_PowerBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_PowerBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_PowerBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PowerBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PowerBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PowerBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_PowerBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_PowerBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_AutoOffTime = lv_dropdown_create(ui_PowerBody);
    lv_dropdown_set_options(ui_AutoOffTime, "Disabled\n2 minutes\n5 minutes\n10 minutes\n20 minutes\n30 minutes");
    lv_obj_set_width(ui_AutoOffTime, lv_pct(100));
    lv_obj_set_height(ui_AutoOffTime, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_AutoOffTime, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_AutoOffTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_AutoOffTime, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_AutoOffTime, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_AutoOffTime, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_AutoOffTime), &ui_font_Inter_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_AutoOffTime), &ui_font_Inter_14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PowerLabel = lv_label_create(ui_PowerBody);
    lv_obj_set_width(ui_PowerLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_PowerLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_PowerLabel, 19);
    lv_obj_set_y(ui_PowerLabel, 38);
    lv_obj_set_align(ui_PowerLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_PowerLabel, "Auto-off time");

    ui_TempUnitsBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_TempUnitsBody);
    lv_obj_set_width(ui_TempUnitsBody, lv_pct(100));
    lv_obj_set_height(ui_TempUnitsBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempUnitsBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_TempUnitsBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_TempUnitsBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_TempUnitsBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_TempUnitsBody, 49, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_TempUnitsBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_TempUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_TempUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_TempUnitsBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_TempUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_TempUnits = lv_dropdown_create(ui_TempUnitsBody);
    lv_dropdown_set_options(ui_TempUnits, "Celsius\nFahrenheit");
    lv_obj_set_width(ui_TempUnits, lv_pct(100));
    lv_obj_set_height(ui_TempUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_TempUnits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_TempUnits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_TempUnits, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_TempUnits, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_TempUnits, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_TempUnits), &ui_font_Inter_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_TempUnits), &ui_font_Inter_14,  LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_TempUnitsLabel = lv_label_create(ui_TempUnitsBody);
    lv_obj_set_width(ui_TempUnitsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TempUnitsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TempUnitsLabel, 19);
    lv_obj_set_y(ui_TempUnitsLabel, 38);
    lv_obj_set_align(ui_TempUnitsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TempUnitsLabel, "Temp units");

    ui_DistanceUnitsBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_DistanceUnitsBody);
    lv_obj_set_width(ui_DistanceUnitsBody, lv_pct(100));
    lv_obj_set_height(ui_DistanceUnitsBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DistanceUnitsBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DistanceUnitsBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DistanceUnitsBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DistanceUnitsBody,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_DistanceUnitsBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DistanceUnitsBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DistanceUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DistanceUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DistanceUnitsBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DistanceUnitsBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DistanceUnits = lv_dropdown_create(ui_DistanceUnitsBody);
    lv_dropdown_set_options(ui_DistanceUnits, "Kilometers\nMiles");
    lv_obj_set_width(ui_DistanceUnits, lv_pct(100));
    lv_obj_set_height(ui_DistanceUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DistanceUnits, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DistanceUnits, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_DistanceUnits, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_DistanceUnits, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_DistanceUnits, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DistanceUnits), &ui_font_Inter_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_DistanceUnits), &ui_font_Inter_14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_DistanceUnitsLabel = lv_label_create(ui_DistanceUnitsBody);
    lv_obj_set_width(ui_DistanceUnitsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DistanceUnitsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DistanceUnitsLabel, 19);
    lv_obj_set_y(ui_DistanceUnitsLabel, 38);
    lv_obj_set_align(ui_DistanceUnitsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DistanceUnitsLabel, "Distance units");

    ui_StartupSoundBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_StartupSoundBody);
    lv_obj_set_width(ui_StartupSoundBody, lv_pct(100));
    lv_obj_set_height(ui_StartupSoundBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartupSoundBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_StartupSoundBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_StartupSoundBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_StartupSoundBody,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_StartupSoundBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_StartupSoundBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_StartupSoundBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_StartupSoundBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_StartupSoundBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_StartupSoundBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_StartupSound = lv_dropdown_create(ui_StartupSoundBody);
    lv_dropdown_set_options(ui_StartupSound, "Disabled\nBeep\nMelody");
    lv_obj_set_width(ui_StartupSound, lv_pct(100));
    lv_obj_set_height(ui_StartupSound, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_StartupSound, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_StartupSound, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_StartupSound, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags
    lv_obj_set_style_text_font(ui_StartupSound, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(ui_StartupSound, &lv_font_montserrat_14, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_StartupSound), &ui_font_Inter_14,  LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_StartupSound), &ui_font_Inter_14,
                               LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_StartupSoundLabel = lv_label_create(ui_StartupSoundBody);
    lv_obj_set_width(ui_StartupSoundLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_StartupSoundLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_StartupSoundLabel, 19);
    lv_obj_set_y(ui_StartupSoundLabel, 38);
    lv_obj_set_align(ui_StartupSoundLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_StartupSoundLabel, "Startup sound");

    ui_ThemeColorBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_ThemeColorBody);
    lv_obj_set_width(ui_ThemeColorBody, lv_pct(100));
    lv_obj_set_height(ui_ThemeColorBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_ThemeColorBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_ThemeColorBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_ThemeColorBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThemeColorBody,
                      LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_SCROLLABLE |
                      LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_ThemeColorBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThemeColorBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThemeColorBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThemeColorBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_ThemeColorBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_ThemeColorBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_ThemeColor = lv_colorwheel_create(ui_ThemeColorBody, true);
    lv_obj_set_width(ui_ThemeColor, 75);
    lv_obj_set_height(ui_ThemeColor, 75);
    lv_obj_set_align(ui_ThemeColor, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ThemeColor, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    lv_obj_set_style_pad_left(ui_ThemeColor, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_ThemeColor, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_ThemeColor, 10, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_ThemeColor, 10, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_ThemeColorLabel = lv_label_create(ui_ThemeColorBody);
    lv_obj_set_width(ui_ThemeColorLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_ThemeColorLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_ThemeColorLabel, 19);
    lv_obj_set_y(ui_ThemeColorLabel, 38);
    lv_obj_set_align(ui_ThemeColorLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_ThemeColorLabel, "Theme color");

    ui_DarkTextBody = lv_obj_create(ui_SettingsBody);
    lv_obj_remove_style_all(ui_DarkTextBody);
    lv_obj_set_width(ui_DarkTextBody, lv_pct(100));
    lv_obj_set_height(ui_DarkTextBody, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DarkTextBody, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_DarkTextBody, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_DarkTextBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_DarkTextBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE |
                      LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM |
                      LV_OBJ_FLAG_SCROLL_CHAIN);     /// Flags
    lv_obj_set_style_pad_left(ui_DarkTextBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_DarkTextBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_DarkTextBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_DarkTextBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_row(ui_DarkTextBody, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_DarkTextBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_DarkText = lv_switch_create(ui_DarkTextBody);
    lv_obj_set_height(ui_DarkText, 25);
    lv_obj_set_width(ui_DarkText, lv_pct(50));
    lv_obj_set_x(ui_DarkText, 31);
    lv_obj_set_y(ui_DarkText, -12);
    lv_obj_set_align(ui_DarkText, LV_ALIGN_CENTER);

    ui_DarkTextLabel = lv_label_create(ui_DarkTextBody);
    lv_obj_set_width(ui_DarkTextLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DarkTextLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DarkTextLabel, 19);
    lv_obj_set_y(ui_DarkTextLabel, 38);
    lv_obj_set_align(ui_DarkTextLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DarkTextLabel, "Dark text");

    ui_SettingsFooter = lv_obj_create(ui_SettingsContent);
    lv_obj_remove_style_all(ui_SettingsFooter);
    lv_obj_set_width(ui_SettingsFooter, lv_pct(100));
    lv_obj_set_height(ui_SettingsFooter, lv_pct(25));
    lv_obj_set_align(ui_SettingsFooter, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_SettingsFooter, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_SettingsFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(ui_SettingsFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_pad_row(ui_SettingsFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_column(ui_SettingsFooter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsMainActionButton = lv_btn_create(ui_SettingsFooter);
    lv_obj_set_width(ui_SettingsMainActionButton, 80);
    lv_obj_set_height(ui_SettingsMainActionButton, 42);
    lv_obj_set_align(ui_SettingsMainActionButton, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SettingsMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_SettingsMainActionButton, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_text_font(ui_SettingsMainActionButton, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_SettingsMainActionButtonLabel = lv_label_create(ui_SettingsMainActionButton);
    lv_obj_set_width(ui_SettingsMainActionButtonLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SettingsMainActionButtonLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_SettingsMainActionButtonLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_SettingsMainActionButtonLabel, "Save");

    lv_obj_add_event_cb(ui_BrightnessSlider, ui_event_BrightnessSlider, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Rotation, ui_event_Rotation, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_AutoOffTime, ui_event_AutoOffTime, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_TempUnits, ui_event_TempUnits, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DistanceUnits, ui_event_DistanceUnits, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_StartupSound, ui_event_StartupSound, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_ThemeColor, ui_event_ThemeColor, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DarkText, ui_event_DarkText, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsMainActionButton, ui_event_SettingsMainActionButton, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_SettingsScreen, ui_event_SettingsScreen, LV_EVENT_ALL, NULL);

}

void ui_SettingsScreen_screen_destroy(void)
{
    if(ui_SettingsScreen) lv_obj_del(ui_SettingsScreen);

    // NULL screen variables
    ui_SettingsScreen = NULL;
    ui_SettingsContent = NULL;
    ui_SettingsHeader = NULL;
    ui_SettingsBody = NULL;
    ui_BrightnessBody = NULL;
    ui_BrightnessSlider = NULL;
    ui_BrightnessLabel = NULL;
    ui_RotationBody = NULL;
    ui_Rotation = NULL;
    ui_RotationLabel = NULL;
    ui_PowerBody = NULL;
    ui_AutoOffTime = NULL;
    ui_PowerLabel = NULL;
    ui_TempUnitsBody = NULL;
    ui_TempUnits = NULL;
    ui_TempUnitsLabel = NULL;
    ui_DistanceUnitsBody = NULL;
    ui_DistanceUnits = NULL;
    ui_DistanceUnitsLabel = NULL;
    ui_StartupSoundBody = NULL;
    ui_StartupSound = NULL;
    ui_StartupSoundLabel = NULL;
    ui_ThemeColorBody = NULL;
    ui_ThemeColor = NULL;
    ui_ThemeColorLabel = NULL;
    ui_DarkTextBody = NULL;
    ui_DarkText = NULL;
    ui_DarkTextLabel = NULL;
    ui_SettingsFooter = NULL;
    ui_SettingsMainActionButton = NULL;
    ui_SettingsMainActionButtonLabel = NULL;

}
