// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_STATSSCREEN_H
#define UI_STATSSCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

  // SCREEN: ui_StatsScreen
  extern void ui_StatsScreen_screen_init(void);
  extern void ui_StatsScreen_screen_destroy(void);
  extern void ui_event_StatsScreen(lv_event_t *e);
  extern lv_obj_t *ui_StatsScreen;
  extern lv_obj_t *ui_SpeedDial;
  extern lv_obj_t *ui_UtilizationDial;
  extern lv_obj_t *ui_LeftSensor;
  extern lv_obj_t *ui_RightSensor;
  extern lv_obj_t *ui_StatsContent;
  extern lv_obj_t *ui_StatsHeader;
  extern lv_obj_t *ui_RemoteIndicatorContainer;
  extern lv_obj_t *ui_BatteryIndicatorContainer;
  extern lv_obj_t *ui_BatteryOutline;
  extern lv_obj_t *ui_BatteryFill;
  extern lv_obj_t *ui_BatteryTip;
  extern lv_obj_t *ui_RSSIContainer;
  extern lv_obj_t *ui_RSSI1;
  extern lv_obj_t *ui_RSSI2;
  extern lv_obj_t *ui_RSSI3;
  extern lv_obj_t *ui_MessageText;
  extern lv_obj_t *ui_StatsBody;
  extern lv_obj_t *ui_RemoteModeContainer;
  extern lv_obj_t *ui_RemoteModeText;
  extern void ui_event_PrimaryStat(lv_event_t *e);
  extern lv_obj_t *ui_PrimaryStat;
  extern lv_obj_t *ui_PrimaryStatUnit;
  extern lv_obj_t *ui_SecondaryStatPaddingContainer;
  extern lv_obj_t *ui_SecondaryStatContainer;
  extern lv_obj_t *ui_ConnectionStateBody;
  extern lv_obj_t *ui_ConnectionStateLabel;
  extern lv_obj_t *ui_DutyCycleBody;
  extern lv_obj_t *ui_DutyCycleLabel;
  extern lv_obj_t *ui_TempsBody;
  extern lv_obj_t *ui_TempsLabel;
  extern lv_obj_t *ui_TripBody;
  extern lv_obj_t *ui_TripLabel;
  extern void ui_event_StatsFooter(lv_event_t *e);
  extern lv_obj_t *ui_StatsFooter;
  extern lv_obj_t *ui_BoardBatteryDisplay;
  // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
