// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_SETTINGSSCREEN_H
#define UI_SETTINGSSCREEN_H

#ifdef __cplusplus
extern "C"
{
#endif

  // SCREEN: ui_SettingsScreen
  extern void ui_SettingsScreen_screen_init(void);
  extern void ui_SettingsScreen_screen_destroy(void);
  extern void ui_event_SettingsScreen(lv_event_t *e);
  extern lv_obj_t *ui_SettingsScreen;
  extern lv_obj_t *ui_SettingsContent;
  extern lv_obj_t *ui_SettingsHeader;
  extern lv_obj_t *ui_SettingsBody;
  extern lv_obj_t *ui_BrightnessBody;
  extern void ui_event_BrightnessSlider(lv_event_t *e);
  extern lv_obj_t *ui_BrightnessSlider;
  extern lv_obj_t *ui_BrightnessLabel;
  extern lv_obj_t *ui_ActionsBody;
  extern void ui_event_DoublePressAction(lv_event_t *e);
  extern lv_obj_t *ui_DoublePressAction;
  extern lv_obj_t *ui_ActionsLabel;
  extern lv_obj_t *ui_RotationBody;
  extern void ui_event_Rotation(lv_event_t *e);
  extern lv_obj_t *ui_Rotation;
  extern lv_obj_t *ui_RotationLabel;
  extern lv_obj_t *ui_PowerBody;
  extern void ui_event_AutoOffTime(lv_event_t *e);
  extern lv_obj_t *ui_AutoOffTime;
  extern lv_obj_t *ui_PowerLabel;
  extern lv_obj_t *ui_TempUnitsBody;
  extern void ui_event_TempUnits(lv_event_t *e);
  extern lv_obj_t *ui_TempUnits;
  extern lv_obj_t *ui_TempUnitsLabel;
  extern lv_obj_t *ui_DistanceUnitsBody;
  extern void ui_event_DistanceUnits(lv_event_t *e);
  extern lv_obj_t *ui_DistanceUnits;
  extern lv_obj_t *ui_DistanceUnitsLabel;
  extern lv_obj_t *ui_StartupSoundBody;
  extern void ui_event_StartupSound(lv_event_t *e);
  extern lv_obj_t *ui_StartupSound;
  extern lv_obj_t *ui_StartupSoundLabel;
  extern lv_obj_t *ui_ThemeColorBody;
  extern void ui_event_ThemeColor(lv_event_t *e);
  extern lv_obj_t *ui_ThemeColor;
  extern lv_obj_t *ui_ThemeColorLabel;
  extern lv_obj_t *ui_DarkTextBody;
  extern void ui_event_DarkText(lv_event_t *e);
  extern lv_obj_t *ui_DarkText;
  extern lv_obj_t *ui_DarkTextLabel;
  extern lv_obj_t *ui_SettingsFooter;
  extern void ui_event_SettingsMainActionButton(lv_event_t *e);
  extern lv_obj_t *ui_SettingsMainActionButton;
  extern lv_obj_t *ui_SettingsMainActionButtonLabel;
  // CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
