// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#include "ui.h"

lv_obj_t *ui_UpdateScreen = NULL;
lv_obj_t *ui_UpdateContent = NULL;
lv_obj_t *ui_UpdateHeader = NULL;
lv_obj_t *ui_UpdateHeaderLabel = NULL;
lv_obj_t *ui_UpdateBody = NULL;
lv_obj_t *ui_UpdateBodyLabel = NULL;
lv_obj_t *ui_UpdateFooter = NULL;
lv_obj_t *ui_UpdateMainActionButton = NULL;
lv_obj_t *ui_UpdateMainActionButtonLabel = NULL;
// event funtions
void ui_event_UpdateScreen(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_SCREEN_LOADED) {
    update_screen_loaded(e);
  }
  if (event_code == LV_EVENT_SCREEN_LOAD_START) {
    update_screen_load_start(e);
  }
  if (event_code == LV_EVENT_SCREEN_UNLOAD_START) {
    update_screen_unload_start(e);
  }
}

void ui_event_UpdateMainActionButton(lv_event_t *e) {
  lv_event_code_t event_code = lv_event_get_code(e);

  if (event_code == LV_EVENT_CLICKED) {
    _ui_screen_change(&ui_MenuScreen, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 200, 0, &ui_MenuScreen_screen_init);
  }
}

// build funtions

void ui_UpdateScreen_screen_init(void) {
  ui_UpdateScreen = lv_obj_create(NULL);
  lv_obj_clear_flag(ui_UpdateScreen, LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_add_event_cb(ui_UpdateScreen, scr_unloaded_delete_cb, LV_EVENT_SCREEN_UNLOADED, &ui_UpdateScreen);
  lv_obj_set_style_bg_color(ui_UpdateScreen, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_bg_opa(ui_UpdateScreen, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateContent = lv_obj_create(ui_UpdateScreen);
  lv_obj_remove_style_all(ui_UpdateContent);
  lv_obj_set_width(ui_UpdateContent, lv_pct(100));
  lv_obj_set_height(ui_UpdateContent, lv_pct(100));
  lv_obj_set_align(ui_UpdateContent, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_UpdateContent, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_UpdateContent, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_UpdateContent, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_text_font(ui_UpdateContent, &ui_font_Inter_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateHeader = lv_obj_create(ui_UpdateContent);
  lv_obj_remove_style_all(ui_UpdateHeader);
  lv_obj_set_width(ui_UpdateHeader, lv_pct(100));
  lv_obj_set_height(ui_UpdateHeader, lv_pct(20));
  lv_obj_set_align(ui_UpdateHeader, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_UpdateHeader, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_UpdateHeader, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_UpdateHeader, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_left(ui_UpdateHeader, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_UpdateHeader, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_UpdateHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_UpdateHeader, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateHeaderLabel = lv_label_create(ui_UpdateHeader);
  lv_obj_set_width(ui_UpdateHeaderLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_UpdateHeaderLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_UpdateHeaderLabel, 31);
  lv_obj_set_y(ui_UpdateHeaderLabel, -102);
  lv_obj_set_align(ui_UpdateHeaderLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_UpdateHeaderLabel, "Update");
  lv_obj_set_style_text_font(ui_UpdateHeaderLabel, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateBody = lv_obj_create(ui_UpdateContent);
  lv_obj_remove_style_all(ui_UpdateBody);
  lv_obj_set_width(ui_UpdateBody, lv_pct(100));
  lv_obj_set_height(ui_UpdateBody, lv_pct(55));
  lv_obj_set_align(ui_UpdateBody, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_UpdateBody, LV_FLEX_FLOW_COLUMN);
  lv_obj_set_flex_align(ui_UpdateBody, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_UpdateBody, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_left(ui_UpdateBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_right(ui_UpdateBody, 40, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_top(ui_UpdateBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_bottom(ui_UpdateBody, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateBodyLabel = lv_label_create(ui_UpdateBody);
  lv_obj_set_width(ui_UpdateBodyLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_UpdateBodyLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_x(ui_UpdateBodyLabel, 19);
  lv_obj_set_y(ui_UpdateBodyLabel, 38);
  lv_obj_set_align(ui_UpdateBodyLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_UpdateBodyLabel, "Wifi: disconnected");

  ui_UpdateFooter = lv_obj_create(ui_UpdateContent);
  lv_obj_remove_style_all(ui_UpdateFooter);
  lv_obj_set_width(ui_UpdateFooter, lv_pct(65));
  lv_obj_set_height(ui_UpdateFooter, lv_pct(25));
  lv_obj_set_align(ui_UpdateFooter, LV_ALIGN_CENTER);
  lv_obj_set_flex_flow(ui_UpdateFooter, LV_FLEX_FLOW_ROW);
  lv_obj_set_flex_align(ui_UpdateFooter, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
  lv_obj_clear_flag(ui_UpdateFooter, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE); /// Flags
  lv_obj_set_style_pad_row(ui_UpdateFooter, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
  lv_obj_set_style_pad_column(ui_UpdateFooter, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateMainActionButton = lv_btn_create(ui_UpdateFooter);
  lv_obj_set_width(ui_UpdateMainActionButton, 80);
  lv_obj_set_height(ui_UpdateMainActionButton, 42);
  lv_obj_set_align(ui_UpdateMainActionButton, LV_ALIGN_CENTER);
  lv_obj_add_flag(ui_UpdateMainActionButton, LV_OBJ_FLAG_SCROLL_ON_FOCUS); /// Flags
  lv_obj_clear_flag(ui_UpdateMainActionButton, LV_OBJ_FLAG_SCROLLABLE);    /// Flags
  lv_obj_set_style_text_font(ui_UpdateMainActionButton, &ui_font_Inter_Bold_14, LV_PART_MAIN | LV_STATE_DEFAULT);

  ui_UpdateMainActionButtonLabel = lv_label_create(ui_UpdateMainActionButton);
  lv_obj_set_width(ui_UpdateMainActionButtonLabel, LV_SIZE_CONTENT);  /// 1
  lv_obj_set_height(ui_UpdateMainActionButtonLabel, LV_SIZE_CONTENT); /// 1
  lv_obj_set_align(ui_UpdateMainActionButtonLabel, LV_ALIGN_CENTER);
  lv_label_set_text(ui_UpdateMainActionButtonLabel, "Cancel");

  lv_obj_add_event_cb(ui_UpdateMainActionButton, ui_event_UpdateMainActionButton, LV_EVENT_ALL, NULL);
  lv_obj_add_event_cb(ui_UpdateScreen, ui_event_UpdateScreen, LV_EVENT_ALL, NULL);
}

void ui_UpdateScreen_screen_destroy(void) {
  if (ui_UpdateScreen)
    lv_obj_del(ui_UpdateScreen);

  // NULL screen variables
  ui_UpdateScreen = NULL;
  ui_UpdateContent = NULL;
  ui_UpdateHeader = NULL;
  ui_UpdateHeaderLabel = NULL;
  ui_UpdateBody = NULL;
  ui_UpdateBodyLabel = NULL;
  ui_UpdateFooter = NULL;
  ui_UpdateMainActionButton = NULL;
  ui_UpdateMainActionButtonLabel = NULL;
}
