// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 8.3.11
// Project name: PubRemote

#ifndef UI_UPDATESCREEN_H
#define UI_UPDATESCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_UpdateScreen
extern void ui_UpdateScreen_screen_init(void);
extern void ui_UpdateScreen_screen_destroy(void);
extern void ui_event_UpdateScreen(lv_event_t * e);
extern lv_obj_t * ui_UpdateScreen;
extern lv_obj_t * ui_UpdateContent;
extern lv_obj_t * ui_UpdateHeader;
extern lv_obj_t * ui_UpdateBody;
extern lv_obj_t * ui_UpdateBodyLabel;
extern lv_obj_t * ui_UpdateBodyDropdown;
extern lv_obj_t * ui_UpdateFooter;
extern void ui_event_UpdateSecondaryActionButton(lv_event_t * e);
extern lv_obj_t * ui_UpdateSecondaryActionButton;
extern lv_obj_t * ui_UpdateSecondaryActionButtonLabel;
extern void ui_event_UpdatePrimaryActionButton(lv_event_t * e);
extern lv_obj_t * ui_UpdatePrimaryActionButton;
extern lv_obj_t * ui_UpdatePrimaryActionButtonLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

