name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Set your default branch here

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # Specify your Node.js version
          
      - name: Install dependencies
        working-directory: ./firmware_tool  # Change to the firmware_tool directory
        run: npm ci  # Using ci instead of install for cleaner installs in CI environment
        
      - name: Build
        working-directory: ./firmware_tool
        run: npm run build  # Assuming you have a build script in package.json
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: firmware_tool/build  # Adjust this to your build output directory
          branch: gh-pages  # The branch the action should deploy to
          clean: true  # Automatically remove deleted files from the deployment
