name: PlatformIO CI

# Runs on every opened, reopened, or updated PR
on:
  pull_request:
    types: 
      - opened
      - reopened
      - synchronize
      - ready_for_review
    branches:
      - master

# References: 
# https://docs.platformio.org/en/stable/integration/ci/github-actions.html
jobs:
  build:
    if: github.repository == 'contactsimonwilson/PubRemote' && github.event.pull_request.draft == false

    runs-on: ubuntu-latest

    steps:
      # Check out the PR branch
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio
          
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PlatformIO Core
        run: pip install --upgrade platformio

      - name: Build PlatformIO Project
        run: pio run -e waveshare_esp32s3_touch_128
        env:
          PLATFORMIO_BUILD_FLAGS: '-D RELEASE_VARIANT=\"release\"'
